import { db } from "@/lib/firebase";
import { collection, doc, serverTimestamp, writeBatch } from "firebase/firestore";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

// Each entry: display name. Slug is auto-derived.
const TEAM_NAMES: string[] = [
  // ── MÉXICO — Liga MX ────────────────────────────────────────
  "América",
  "Chivas",
  "Cruz Azul",
  "Pumas",
  "Tigres",
  "Monterrey",
  "Toluca",
  "Santos Laguna",
  "Atlas",
  "León",
  "Necaxa",
  "Querétaro",
  "Mazatlán",
  "Juárez",
  "San Luis",
  "Tijuana",
  "Puebla",
  "Pachuca",
  "Atlético San Luis",
  "Guadalajara",

  // ── USA — MLS ────────────────────────────────────────────────
  "LA Galaxy",
  "Inter Miami",
  "LAFC",
  "Seattle Sounders",
  "Portland Timbers",
  "Atlanta United",
  "New York City FC",
  "New York Red Bulls",
  "Chicago Fire",
  "Houston Dynamo",
  "Real Salt Lake",
  "Colorado Rapids",
  "Vancouver Whitecaps",
  "Toronto FC",
  "CF Montréal",
  "Orlando City",
  "DC United",
  "New England Revolution",
  "Columbus Crew",
  "FC Dallas",
  "Austin FC",
  "Charlotte FC",
  "Nashville SC",
  "Philadelphia Union",
  "Sporting Kansas City",
  "Minnesota United",
  "San Jose Earthquakes",
  "FC Cincinnati",

  // ── ESPAÑA — La Liga ─────────────────────────────────────────
  "Real Madrid",
  "Barcelona",
  "Atlético de Madrid",
  "Sevilla",
  "Valencia",
  "Villarreal",
  "Athletic Club",
  "Real Sociedad",
  "Betis",
  "Celta de Vigo",
  "Osasuna",
  "Getafe",
  "Rayo Vallecano",
  "Espanyol",
  "Mallorca",
  "Girona",
  "Las Palmas",

  // ── ENGLAND — Premier League ─────────────────────────────────
  "Manchester City",
  "Arsenal",
  "Liverpool",
  "Chelsea",
  "Manchester United",
  "Tottenham",
  "Newcastle",
  "Aston Villa",
  "Brighton",
  "West Ham",
  "Brentford",
  "Fulham",
  "Crystal Palace",
  "Wolves",
  "Nottingham Forest",
  "Everton",
  "Bournemouth",

  // ── GERMANY — Bundesliga ─────────────────────────────────────
  "Bayern Munich",
  "Borussia Dortmund",
  "RB Leipzig",
  "Bayer Leverkusen",
  "Wolfsburg",
  "Eintracht Frankfurt",
  "Borussia Mönchengladbach",
  "Stuttgart",
  "Werder Bremen",
  "Hoffenheim",
  "Augsburg",
  "Mainz",

  // ── ITALY — Serie A ──────────────────────────────────────────
  "Juventus",
  "Inter Milan",
  "AC Milan",
  "Napoli",
  "Roma",
  "Lazio",
  "Fiorentina",
  "Atalanta",
  "Torino",
  "Bologna",
  "Udinese",
  "Monza",

  // ── FRANCE — Ligue 1 ─────────────────────────────────────────
  "PSG",
  "Marseille",
  "Lyon",
  "Monaco",
  "Lille",
  "Nice",
  "Rennes",
  "Lens",
  "Nantes",
  "Montpellier",
  "Toulouse",
  "Reims",
  "Brest",

  // ── ARGENTINA ────────────────────────────────────────────────
  "River Plate",
  "Boca Juniors",
  "Racing Club",
  "Independiente",
  "San Lorenzo",
  "Estudiantes",
  "Vélez Sársfield",
  "Huracán",
  "Talleres",
  "Newell's Old Boys",
  "Rosario Central",
  "Lanús",
  "Banfield",
  "Defensa y Justicia",
  "Gimnasia La Plata",
  "Belgrano",
  "Tigre",
  "Godoy Cruz",
  "Colón",
  "Unión Santa Fe",

  // ── BRASIL ───────────────────────────────────────────────────
  "Flamengo",
  "Palmeiras",
  "São Paulo",
  "Corinthians",
  "Santos",
  "Grêmio",
  "Internacional",
  "Cruzeiro",
  "Atlético Mineiro",
  "Fluminense",
  "Vasco da Gama",
  "Botafogo",
  "Bahia",
  "Fortaleza",
  "Athletico Paranaense",
  "Coritiba",
  "Goiás",
  "Sport Recife",

  // ── COLOMBIA ─────────────────────────────────────────────────
  "Atlético Nacional",
  "Millonarios",
  "América de Cali",
  "Junior",
  "Deportivo Cali",
  "Santa Fe",
  "Once Caldas",
  "Deportes Tolima",
  "Peñarol Bogotá",
  "Envigado",

  // ── CHILE ────────────────────────────────────────────────────
  "Colo-Colo",
  "Universidad de Chile",
  "Universidad Católica",
  "Audax Italiano",
  "Unión Española",
  "Huachipato",
  "Cobresal",
  "La Serena",
  "Palestino",
  "Curicó Unido",

  // ── PERÚ ─────────────────────────────────────────────────────
  "Alianza Lima",
  "Universitario",
  "Sporting Cristal",
  "FBC Melgar",
  "Binacional",
  "Cienciano",
  "Mannucci",
  "Municipal",
  "Sport Huancayo",
  "Ayacucho FC",

  // ── ECUADOR ──────────────────────────────────────────────────
  "Barcelona SC",
  "Emelec",
  "Liga de Quito",
  "Independiente del Valle",
  "Deportivo Cuenca",
  "El Nacional",
  "Aucas",
  "Delfín",
  "Técnico Universitario",
  "Macará",

  // ── VENEZUELA ────────────────────────────────────────────────
  "Caracas FC",
  "Deportivo Táchira",
  "Estudiantes de Mérida",
  "Mineros de Guayana",
  "Monagas SC",
  "Carabobo FC",
  "Zamora FC",
  "Metropolitanos",

  // ── URUGUAY ──────────────────────────────────────────────────
  "Peñarol",
  "Nacional",
  "Defensor Sporting",
  "Danubio",
  "River Plate Uruguay",
  "Fénix",
  "Liverpool Uruguay",
  "Rampla Juniors",
  "Plaza Colonia",

  // ── PARAGUAY ─────────────────────────────────────────────────
  "Olimpia",
  "Cerro Porteño",
  "Libertad",
  "Guaraní",
  "Sol de América",
  "Nacional Asunción",
  "Sportivo Luqueño",
  "Tacuary",
  "12 de Octubre",

  // ── BOLIVIA ──────────────────────────────────────────────────
  "Bolívar",
  "The Strongest",
  "Blooming",
  "Oriente Petrolero",
  "Wilstermann",
  "Always Ready",
  "Nacional Potosí",
  "Aurora",

  // ── HONDURAS ─────────────────────────────────────────────────
  "Real España",
  "Olimpia Honduras",
  "Motagua",
  "Marathon",
  "Platense Honduras",
  "Victoria",
  "UPNFM",
  "Juticalpa FC",
  "Real de Minas",
  "Lobos UPNFM",

  // ── EL SALVADOR ──────────────────────────────────────────────
  "Alianza FC El Salvador",
  "FAS",
  "Águila El Salvador",
  "Firpo",
  "Once Municipal",
  "CD Dragón",
  "Jocoro FC",
  "Santa Tecla FC",
  "Metapán",
  "Isidro Metapán",

  // ── GUATEMALA ────────────────────────────────────────────────
  "Municipal Guatemala",
  "Comunicaciones FC",
  "Antigua GFC",
  "Deportivo Petapa",
  "Xelajú MC",
  "Cobán Imperial",
  "Guastatoya",
  "CSD Siquinalá",
  "Malacateco",
  "Deportivo Mixco",

  // ── COSTA RICA ───────────────────────────────────────────────
  "Alajuelense",
  "Saprissa",
  "Herediano",
  "Cartaginés",
  "Liberia Mía",
  "Santos de Guápiles",
  "Pérez Zeledón",
  "Jicaral",
  "Guadalupe FC",
  "San Carlos",

  // ── PANAMÁ ───────────────────────────────────────────────────
  "Tauro FC",
  "Árabe Unido",
  "Plaza Amador",
  "Sporting San Miguelito",
  "Universitario Panamá",
  "CAI",
  "Atlético Chiriquí",
  "Chorrillo FC",

  // ── NICARAGUA ────────────────────────────────────────────────
  "Real Estelí",
  "Diriangén",
  "Walter Ferretti",
  "Deportivo Ocotal",
  "Chinandega FC",
  "Juventus Nicaragua",

  // ── REPÚBLICA DOMINICANA ─────────────────────────────────────
  "Cibao FC",
  "Atlántico FC",
  "Moca FC",
  "Plaza Fútbol",
  "Bauger FC",

  // ── CUBA ─────────────────────────────────────────────────────
  "Villa Clara",
  "Santiago de Cuba",
  "Pinar del Río",
  "Cienfuegos FC",
  "La Habana FC",

  // ── SELECCIONES — CONCACAF ───────────────────────────────────
  "Selección México",
  "Selección Estados Unidos",
  "Selección Canadá",
  "Selección Costa Rica",
  "Selección Honduras",
  "Selección El Salvador",
  "Selección Guatemala",
  "Selección Panamá",
  "Selección Jamaica",
  "Selección Trinidad y Tobago",
  "Selección Haití",
  "Selección Nicaragua",
  "Selección Cuba",
  "Selección República Dominicana",
  "Selección Curaçao",
  "Selección Bermuda",
  "Selección Barbados",
  "Selección Belice",
  "Selección Guyana",
  "Selección Surinam",

  // ── SELECCIONES — SUDAMÉRICA ─────────────────────────────────
  "Selección Argentina",
  "Selección Brasil",
  "Selección Uruguay",
  "Selección Colombia",
  "Selección Chile",
  "Selección Perú",
  "Selección Ecuador",
  "Selección Paraguay",
  "Selección Bolivia",
  "Selección Venezuela",

  // ── SELECCIONES — EUROPA ─────────────────────────────────────
  "Selección España",
  "Selección Francia",
  "Selección Alemania",
  "Selección Italia",
  "Selección Inglaterra",
  "Selección Portugal",
  "Selección Países Bajos",
  "Selección Bélgica",
  "Selección Croacia",
  "Selección Serbia",
  "Selección Suiza",
  "Selección Dinamarca",
  "Selección Suecia",
  "Selección Noruega",
  "Selección Austria",
  "Selección Escocia",
  "Selección Polonia",
  "Selección Ucrania",
  "Selección Turquía",
  "Selección República Checa",
  "Selección Hungría",
  "Selección Rumania",
  "Selección Grecia",
  "Selección Eslovaquia",
  "Selección Eslovenia",
  "Selección Albania",
  "Selección Macedonia del Norte",
  "Selección Montenegro",
  "Selección Bosnia y Herzegovina",
  "Selección Georgia",
  "Selección Armenia",

  // ── SELECCIONES — ÁFRICA ─────────────────────────────────────
  "Selección Marruecos",
  "Selección Senegal",
  "Selección Nigeria",
  "Selección Ghana",
  "Selección Camerún",
  "Selección Costa de Marfil",
  "Selección Mali",
  "Selección Argelia",
  "Selección Túnez",
  "Selección Egipto",
  "Selección Sudáfrica",
  "Selección Zimbabwe",
  "Selección Uganda",
  "Selección Tanzania",
  "Selección Kenia",
  "Selección RD Congo",
  "Selección Cabo Verde",
  "Selección Guinea",
  "Selección Guinea-Bisáu",
  "Selección Mozambique",
  "Selección Angola",
  "Selección Zambia",
  "Selección Burkina Faso",

  // ── SELECCIONES — ASIA ───────────────────────────────────────
  "Selección Japón",
  "Selección Corea del Sur",
  "Selección Arabia Saudita",
  "Selección Irán",
  "Selección Australia",
  "Selección Qatar",
  "Selección Irak",
  "Selección Emiratos Árabes",
  "Selección Omán",
  "Selección China",
  "Selección India",
  "Selección Vietnam",
  "Selección Tailandia",
  "Selección Indonesia",
  "Selección Uzbekistán",
  "Selección Kazajistán",
  "Selección Siria",
  "Selección Líbano",
  "Selección Jordania",
  "Selección Palestina",
  "Selección Baréin",
  "Selección Kuwait",
  "Selección Kirguistán",
  "Selección Tayikistán",

  // ── SELECCIONES — OCEANÍA ────────────────────────────────────
  "Selección Nueva Zelanda",
  "Selección Fiji",
  "Selección Papua Nueva Guinea",
  "Selección Solomon Islands",
  "Selección Tahití",
  "Selección Vanuatu",
  "Selección Samoa",
];

export async function seedWorldTeams(): Promise<number> {
  const teamsCol = collection(db, "teams");
  const BATCH_SIZE = 499;
  let count = 0;

  for (let i = 0; i < TEAM_NAMES.length; i += BATCH_SIZE) {
    const batch = writeBatch(db);
    const chunk = TEAM_NAMES.slice(i, i + BATCH_SIZE);
    for (const name of chunk) {
      const slug = slugify(name);
      const ref = doc(teamsCol, slug);
      batch.set(
        ref,
        { name, slug, source: "seed", createdAt: serverTimestamp() },
        { merge: true }
      );
      count++;
    }
    await batch.commit();
  }

  return count;
}
