// src/lib/firestore/seedFanZones.ts
// Llamar UNA SOLA VEZ desde el admin panel para poblar wc2026_fanzones.
// Usa setDoc con IDs explícitos para que sea idempotente (safe to re-run).
import { db } from "../firebase";
import { doc, setDoc, serverTimestamp } from "firebase/firestore";
import type { FanZone } from "./fanzones";

type SeedRow = Omit<FanZone, "id" | "updatedAt">;

const FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── USA — FIFA FAN FESTIVALS OFICIALES ───────────────────────────────────
  {
    id: "fan-festival-philadelphia",
    type: "fan_festival",
    name: "FIFA Fan Festival Philadelphia",
    city: "Philadelphia",
    country: "usa",
    venue: "Lemon Hill, Fairmount Park",
    address: "1 Lemon Hill Drive, Philadelphia, PA 19130",
    lat: 40.7684,
    lng: -75.1838,
    entry: "Gratuita, requiere registro anticipado",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://phillyfwc26.com/fifa-fan-fest",
    registrationUrl: "https://phillyfwc26.com/fifa-fan-fest",
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-dallas",
    type: "fan_festival",
    name: "FIFA Fan Festival Dallas",
    city: "Dallas",
    country: "usa",
    venue: "Fair Park",
    address: "3809 Grand Ave, Dallas, TX 75210",
    lat: 32.7802,
    lng: -96.7492,
    entry: "Gratuita, sin registro requerido",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://www.dallasfwc26.com/our-venues/fan-festival/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-houston",
    type: "fan_festival",
    name: "FIFA Fan Festival Houston",
    city: "Houston",
    country: "usa",
    venue: "East Downtown (EaDo), cerca de Shell Energy Stadium",
    address: "East Downtown, Houston, TX 77003",
    lat: 29.7523,
    lng: -95.3518,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026 (34 días)",
    officialUrl: "https://www.fwc26houston.com/fifafanfestivalhou",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-kansas-city",
    type: "fan_festival",
    name: "FIFA Fan Festival Kansas City",
    city: "Kansas City",
    country: "usa",
    venue: "National WWI Museum and Memorial",
    address: "2 Memorial Dr, Kansas City, MO 64108",
    lat: 39.0997,
    lng: -94.5786,
    entry: "Gratuita, requiere pase digital anticipado",
    datesOpen: "11 jun – 13 jul 2026 (18 días)",
    officialUrl: "https://kansascityfwc26.com/fifa-fan-festival/",
    registrationUrl: "https://kansascityfwc26.com/fifa-fan-festival/",
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-miami",
    type: "fan_festival",
    name: "FIFA Fan Festival Miami",
    city: "Miami",
    country: "usa",
    venue: "Bayfront Park",
    address: "301 Biscayne Blvd, Miami, FL 33132",
    lat: 25.7751,
    lng: -80.1839,
    entry: "Gratuita",
    datesOpen: "13 jun – 5 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-atlanta",
    type: "fan_festival",
    name: "FIFA Fan Festival Atlanta",
    city: "Atlanta",
    country: "usa",
    venue: "Centennial Olympic Park",
    address: "235 Park Ave SW, Atlanta, GA 30313",
    lat: 33.7601,
    lng: -84.3922,
    entry: "Gratuita",
    datesOpen: "20 días durante el torneo",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-boston",
    type: "fan_festival",
    name: "FIFA Fan Festival Boston",
    city: "Boston",
    country: "usa",
    venue: "City Hall Plaza",
    address: "City Hall Plaza, Boston, MA 02201",
    lat: 42.3601,
    lng: -71.0589,
    entry: "TBC",
    datesOpen: "Hasta 16 días en jun 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-los-angeles",
    type: "fan_festival",
    name: "FIFA Fan Festival Los Angeles",
    city: "Los Angeles",
    country: "usa",
    venue: "LA Memorial Coliseum",
    address: "3911 S Figueroa St, Los Angeles, CA 90037",
    lat: 34.0141,
    lng: -118.2879,
    entry: "Desde $10 (niños 12 y menor gratis)",
    datesOpen: "11 jun – 14 jun 2026",
    officialUrl: "https://losangelesfwc26.com/fifa-fan-festival-los-angeles/",
    registrationUrl: "https://losangelesfwc26.com/fifa-fan-festival-los-angeles/",
    notes: null,
    active: true,
  },

  // ─── USA — FAN ZONES BAY AREA ─────────────────────────────────────────────
  {
    id: "fan-zone-thrive-city-sf",
    type: "fan_zone",
    name: "Thrive City Fan Zone",
    city: "San Francisco",
    country: "usa",
    venue: "Thrive City, Chase Center",
    address: "1 Warriors Way, San Francisco, CA 94158",
    lat: 37.7679,
    lng: -122.3874,
    entry: "Gratuita",
    datesOpen: "18 jun 2026 (México vs Corea del Sur)",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-zone-san-pedro-square-sj",
    type: "fan_zone",
    name: "San Pedro Square Market Fan Zone",
    city: "San Jose",
    country: "usa",
    venue: "San Pedro Square Market",
    address: "87 N San Pedro St, San Jose, CA 95110",
    lat: 37.3363,
    lng: -121.895,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Hub principal del Bay Area. Venues adicionales por confirmar.",
    active: true,
  },

  // ─── USA — FAN ZONES NEW YORK ─────────────────────────────────────────────
  {
    id: "fan-zone-queens-ny",
    type: "fan_zone",
    name: "Fan Zone Queens",
    city: "New York",
    country: "usa",
    venue: "Louis Armstrong Stadium, USTA Billie Jean King Center",
    address: "124-02 Roosevelt Ave, Corona, NY 11368",
    lat: 40.7498,
    lng: -73.8458,
    entry: "Gratuita, requiere ticket anticipado (Live Nation)",
    datesOpen: "17 jun – 28 jun 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: "https://nynjfwc26.com/fan-zones/",
    notes: null,
    active: true,
  },
  {
    id: "fan-village-rockefeller-ny",
    type: "fan_zone",
    name: "Fan Village Rockefeller Center",
    city: "New York",
    country: "usa",
    venue: "Rockefeller Center",
    address: "45 Rockefeller Plaza, New York, NY 10111",
    lat: 40.7587,
    lng: -73.9787,
    entry: "Gratuita",
    datesOpen: "4 jul – 19 jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-hub-harrison-nj",
    type: "fan_zone",
    name: "NYNJ Jersey Fan Hub",
    city: "Harrison, NJ",
    country: "usa",
    venue: "Sports Illustrated Stadium",
    address: "1 Sports Dr, Harrison, NJ 07029",
    lat: 40.7417,
    lng: -74.1554,
    entry: "Gratuita",
    datesOpen: "Fechas selectas Jun–Jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── CANADÁ ───────────────────────────────────────────────────────────────
  {
    id: "fan-festival-toronto",
    type: "fan_festival",
    name: "FIFA Fan Festival Toronto",
    city: "Toronto",
    country: "canada",
    venue: "Fort York National Historic Site",
    address: "250 Fort York Blvd, Toronto, ON M5V 3K9",
    lat: 43.6359,
    lng: -79.4005,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-vancouver",
    type: "fan_festival",
    name: "FIFA Fan Festival Vancouver",
    city: "Vancouver",
    country: "canada",
    venue: "Hastings Park",
    address: "Hastings Park, Vancouver, BC V5K 0A1",
    lat: 49.2827,
    lng: -123.0348,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── MÉXICO ───────────────────────────────────────────────────────────────
  {
    id: "fan-festival-cdmx",
    type: "fan_festival",
    name: "FIFA Fan Festival Ciudad de México",
    city: "Ciudad de México",
    country: "mexico",
    venue: "El Zócalo (Plaza de la Constitución)",
    address: "Plaza de la Constitución S/N, Centro Histórico, CDMX",
    lat: 19.4326,
    lng: -99.1332,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Espacios adicionales en las alcaldías de CDMX",
    active: true,
  },
  {
    id: "fan-festival-monterrey",
    type: "fan_festival",
    name: "FIFA Fan Festival Monterrey",
    city: "Monterrey",
    country: "mexico",
    venue: "Parque Fundidora",
    address: "Av. Fundidora 501, Obrera, Monterrey, N.L.",
    lat: 25.6777,
    lng: -100.285,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://www.fwc26monterrey.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-guadalajara",
    type: "fan_festival",
    name: "FIFA Fan Festival Guadalajara",
    city: "Guadalajara",
    country: "mexico",
    venue: "Plaza Liberación",
    address: "C. Pedro Loza 27A, Zona Centro, 44100 Guadalajara, Jal.",
    lat: 20.6597,
    lng: -103.3496,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Espacios alternos en Zapopan: Parque Rojo, Plaza Las Américas",
    active: true,
  },
];

export async function seedFanZones(): Promise<void> {
  for (const { id, ...data } of FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedFanZones complete — ${FAN_ZONES.length} documents written.`);
}

// ─── NUEVOS FAN ZONES — Abril 2026 ────────────────────────────────────────────
// Solo agregar. No sobreescribe los documentos existentes (IDs diferentes).
const NEW_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── NUEVA YORK — Fan Zones adicionales ─────────────────────────────────────
  {
    id: "ny-brooklyn",
    type: "fan_zone",
    name: "Fan Zone Brooklyn",
    city: "Brooklyn",
    country: "usa",
    venue: "Brooklyn Bridge Park",
    address: "334 Furman St, Brooklyn, NY 11201",
    lat: 40.7022,
    lng: -73.9965,
    entry: "Gratuita",
    datesOpen: "13 jun – 19 jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "ny-staten-island",
    type: "fan_zone",
    name: "Fan Zone Staten Island",
    city: "Staten Island",
    country: "usa",
    venue: "FerryHawks SIUH Community Park",
    address: "2401 Richmond Ave, Staten Island, NY 10314",
    lat: 40.6469,
    lng: -74.0768,
    entry: "Gratuita",
    datesOpen: "29 jun – 2 jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "ny-bronx",
    type: "fan_zone",
    name: "Fan Zone El Bronx",
    city: "Bronx",
    country: "usa",
    venue: "Bronx Terminal Market",
    address: "610 Exterior St, Bronx, NY 10451",
    lat: 40.8236,
    lng: -73.9286,
    entry: "Gratuita",
    datesOpen: "13–14 jun 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "nj-jersey-city",
    type: "fan_zone",
    name: "Jersey Fan Hub",
    city: "Jersey City",
    country: "usa",
    venue: "Liberty State Park",
    address: "1 Audrey Zapp Dr, Jersey City, NJ 07305",
    lat: 40.7042,
    lng: -74.0531,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── LOS ÁNGELES — Fan Zones adicionales ────────────────────────────────────
  {
    id: "la-union-station",
    type: "fan_zone",
    name: "Fan Zone Union Station",
    city: "Los Angeles",
    country: "usa",
    venue: "Union Station",
    address: "800 N Alameda St, Los Angeles, CA 90012",
    lat: 34.0562,
    lng: -118.2365,
    entry: "Gratuita",
    datesOpen: "25–28 jun 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-hansen-dam",
    type: "fan_zone",
    name: "Fan Zone Hansen Dam",
    city: "Lake View Terrace",
    country: "usa",
    venue: "Hansen Dam Recreation Area",
    address: "11770 Foothill Blvd, Lake View Terrace, CA 91342",
    lat: 34.2709,
    lng: -118.3842,
    entry: "Gratuita",
    datesOpen: "2–5 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-magic-johnson-park",
    type: "fan_zone",
    name: "Fan Zone Earvin Magic Johnson Park",
    city: "Willowbrook",
    country: "usa",
    venue: "Earvin Magic Johnson Park",
    address: "905 E El Segundo Blvd, Willowbrook, CA 90222",
    lat: 33.9163,
    lng: -118.2581,
    entry: "Gratuita",
    datesOpen: "4–5 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-whittier-narrows",
    type: "fan_zone",
    name: "Fan Zone Whittier Narrows",
    city: "South El Monte",
    country: "usa",
    venue: "Whittier Narrows Recreation Area",
    address: "750 S Santa Anita Ave, South El Monte, CA 91733",
    lat: 34.0372,
    lng: -118.0669,
    entry: "Gratuita",
    datesOpen: "9–11 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-fairplex",
    type: "fan_zone",
    name: "Fan Zone Fairplex Pomona",
    city: "Pomona",
    country: "usa",
    venue: "Fairplex",
    address: "1101 W McKinley Ave, Pomona, CA 91768",
    lat: 34.0850,
    lng: -117.7667,
    entry: "Gratuita",
    datesOpen: "14–15 y 18–19 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-west-harbor",
    type: "fan_zone",
    name: "Fan Zone West Harbor Waterfront",
    city: "San Pedro",
    country: "usa",
    venue: "West Harbor Waterfront",
    address: "1200 Nagoya Way, San Pedro, CA 90731",
    lat: 33.7401,
    lng: -118.2783,
    entry: "Gratuita",
    datesOpen: "14–15 y 18–19 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-burbank",
    type: "fan_zone",
    name: "Fan Zone Downtown Burbank",
    city: "Burbank",
    country: "usa",
    venue: "San Fernando Blvd",
    address: "San Fernando Blvd, Burbank, CA 91502",
    lat: 34.1808,
    lng: -118.3090,
    entry: "Gratuita",
    datesOpen: "18–19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── BAY AREA — Fan Zones adicionales ───────────────────────────────────────
  {
    id: "sf-china-basin",
    type: "fan_zone",
    name: "Fan Zone China Basin Park",
    city: "San Francisco",
    country: "usa",
    venue: "China Basin Park at Mission Rock",
    address: "China Basin Park, San Francisco, CA 94107",
    lat: 37.7751,
    lng: -122.3893,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },
  {
    id: "sf-pier39",
    type: "fan_zone",
    name: "Fan Zone PIER 39",
    city: "San Francisco",
    country: "usa",
    venue: "PIER 39",
    address: "Beach St & The Embarcadero, San Francisco, CA 94133",
    lat: 37.8087,
    lng: -122.4098,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },
  {
    id: "oak-raimondi-park",
    type: "fan_zone",
    name: "Fan Zone Raimondi Park Oakland",
    city: "Oakland",
    country: "usa",
    venue: "Raimondi Park",
    address: "1360 3rd Ave, Oakland, CA 94606",
    lat: 37.7849,
    lng: -122.2477,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },

  // ─── WASHINGTON STATE — Fan Zones del gobierno estatal ───────────────────────
  {
    id: "wa-bellingham",
    type: "fan_zone",
    name: "Fan Zone Bellingham",
    city: "Bellingham",
    country: "usa",
    venue: "Kulshan Brewing Trackside",
    address: "Bellingham, WA",
    lat: 48.7492,
    lng: -122.4842,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Bellingham",
    active: true,
  },
  {
    id: "wa-tacoma",
    type: "fan_zone",
    name: "Fan Zone Tacoma",
    city: "Tacoma",
    country: "usa",
    venue: "Puyallup Tribal Headquarters",
    address: "Tacoma, WA",
    lat: 47.2415,
    lng: -122.4102,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por Puyallup Tribe y ciudad de Tacoma",
    active: true,
  },
  {
    id: "wa-spokane",
    type: "fan_zone",
    name: "Fan Zone Spokane",
    city: "Spokane",
    country: "usa",
    venue: "Riverfront Park — Gesa Pavilion",
    address: "507 N Howard St, Spokane, WA 99201",
    lat: 47.6616,
    lng: -117.4202,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Spokane",
    active: true,
  },
  {
    id: "wa-everett",
    type: "fan_zone",
    name: "Fan Zone Everett",
    city: "Everett",
    country: "usa",
    venue: "Boxcar Park",
    address: "Everett, WA",
    lat: 47.9861,
    lng: -122.2173,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Everett",
    active: true,
  },
  {
    id: "wa-olympia",
    type: "fan_zone",
    name: "Fan Zone Olympia",
    city: "Olympia",
    country: "usa",
    venue: "Port Plaza",
    address: "Olympia, WA",
    lat: 47.0505,
    lng: -122.9067,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por Port of Olympia",
    active: true,
  },
  {
    id: "wa-yakima",
    type: "fan_zone",
    name: "Fan Zone Yakima",
    city: "Yakima",
    country: "usa",
    venue: "Sozo Sports Complex",
    address: "5801 Occidental Rd, Yakima, WA 98903",
    lat: 46.5642,
    lng: -120.5481,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por Yakima Host Committee",
    active: true,
  },
];

export async function seedNewFanZones(): Promise<void> {
  for (const { id, ...data } of NEW_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded new fan zone: ${id}`);
  }
  console.log(`seedNewFanZones complete — ${NEW_FAN_ZONES.length} documents written.`);
}

// ─── CDMX + GUADALAJARA — 30 abril 2026 ──────────────────────────────────────
// 9 Festivales Futboleros CDMX (anunciados por Clara Brugada) +
// 4 Fan Zones de Zapopan (gobierno municipal)
const CDMX_GDL_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── CIUDAD DE MÉXICO ────────────────────────────────────────────────────────
  {
    id: "cdmx-chapultepec-cricri",
    type: "fan_zone",
    name: "Festival Futbolero Parque Cri-Cri",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Cri-Cri, Bosque de Chapultepec 3a Sección",
    address: "Bosque de Chapultepec, Miguel Hidalgo, CDMX",
    lat: 19.4180,
    lng: -99.2050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-utopia-meyehualco",
    type: "fan_zone",
    name: "Festival Futbolero Utopía Meyehualco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Utopía Meyehualco",
    address: "Iztapalapa, CDMX",
    lat: 19.3450,
    lng: -99.0420,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-campos-revolucion",
    type: "fan_zone",
    name: "Festival Futbolero Campos Revolución",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Campos Revolución",
    address: "Gustavo A. Madero, CDMX",
    lat: 19.4850,
    lng: -99.1180,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-monumento-revolucion",
    type: "fan_zone",
    name: "Festival Futbolero Monumento a la Revolución",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Monumento a la Revolución",
    address: "Plaza de la República, Cuauhtémoc, CDMX",
    lat: 19.4339,
    lng: -99.1502,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Transmite partidos de México y encuentros destacados.",
    active: true,
  },
  {
    id: "cdmx-deportivo-galeana",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Hermanos Galeana",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Hermanos Galeana",
    address: "Gustavo A. Madero, CDMX",
    lat: 19.4950,
    lng: -99.1050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Transmite partidos de México y encuentros destacados.",
    active: true,
  },
  {
    id: "cdmx-iztapalapa",
    type: "fan_zone",
    name: "Festival Futbolero Iztapalapa",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Iztapalapa",
    address: "Iztapalapa, CDMX",
    lat: 19.3557,
    lng: -99.0554,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-coyoacan",
    type: "fan_zone",
    name: "Festival Futbolero Coyoacán",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Coyoacán",
    address: "Coyoacán, CDMX",
    lat: 19.3467,
    lng: -99.1617,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-tlalpan",
    type: "fan_zone",
    name: "Festival Futbolero Tlalpan",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Tlalpan",
    address: "Tlalpan, CDMX",
    lat: 19.2969,
    lng: -99.1661,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-xochimilco",
    type: "fan_zone",
    name: "Festival Futbolero Xochimilco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Xochimilco",
    address: "Xochimilco, CDMX",
    lat: 19.2571,
    lng: -99.1043,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },

  // ─── GUADALAJARA / ZAPOPAN ────────────────────────────────────────────────────
  {
    id: "gdl-parque-rojo",
    type: "fan_zone",
    name: "Fan Zone Parque Rojo",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque Rojo",
    address: "Av. Vallarta / Juárez, Zapopan, Jalisco",
    lat: 20.6750,
    lng: -103.3551,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-parque-la-mujer",
    type: "fan_zone",
    name: "Fan Zone Parque La Mujer",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque La Mujer",
    address: "C. Santa Lucía, Zapopan, Jalisco",
    lat: 20.7300,
    lng: -103.4200,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-parque-ninas-ninos",
    type: "fan_zone",
    name: "Fan Zone Parque de Las Niñas y Los Niños",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque de Las Niñas y Los Niños",
    address: "Prolongación Laureles, Zapopan, Jalisco",
    lat: 20.7250,
    lng: -103.3950,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-plaza-las-americas",
    type: "fan_zone",
    name: "Fan Zone Plaza Las Américas",
    city: "Zapopan",
    country: "mexico",
    venue: "Plaza Las Américas",
    address: "Centro de Zapopan, Jalisco",
    lat: 20.7215,
    lng: -103.3925,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 10,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
];

export async function seedCdmxGdlFanZones(): Promise<void> {
  for (const { id, ...data } of CDMX_GDL_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedCdmxGdlFanZones complete — ${CDMX_GDL_FAN_ZONES.length} documents written.`);
}

// ─── CANADÁ — 30 abril 2026 ───────────────────────────────────────────────────
// IDs nuevos con información corregida. Los viejos (fan-festival-toronto,
// fan-festival-vancouver) se desactivan vía patchFanZones().
const CANADA_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  {
    id: "canada-toronto",
    type: "fan_festival",
    name: "FIFA Fan Festival Toronto",
    city: "Toronto",
    country: "canada",
    venue: "Fort York National Historic Site",
    address: "250 Fort York Blvd, Toronto, ON M5V 3K9",
    lat: 43.6359,
    lng: -79.4005,
    entry: "Gratuita",
    datesOpen: "12 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Bajo el lema The World in a City. Destaca la diversidad multicultural de Toronto.",
    active: true,
  },
  {
    id: "canada-vancouver",
    type: "fan_festival",
    name: "FIFA Fan Festival Vancouver",
    city: "Vancouver",
    country: "canada",
    venue: "Hastings Park — PNE Grounds",
    address: "2901 E Hastings St, Vancouver, BC V5K 0A1",
    lat: 49.2827,
    lng: -123.0348,
    entry: "Gratuita (asientos reservados en anfiteatro ticketados)",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Anfiteatro de 10,000 personas. Conciertos: Mötley Crüe y Kx5 (Deadmau5 + Kaskade) en julio.",
    active: true,
  },
];

export async function seedCanadaFanZones(): Promise<void> {
  for (const { id, ...data } of CANADA_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedCanadaFanZones complete — ${CANADA_FAN_ZONES.length} documents written.`);
}

// ─── PARCHES — correcciones sobre documentos ya existentes ───────────────────
// Usa setDoc con merge:true para no sobreescribir campos no mencionados.
type PatchRow = { id: string } & Record<string, unknown>;

const PATCHES: PatchRow[] = [
  // Rockefeller: era fan_zone genérico → es fan_festival FIFA x Telemundo
  {
    id: "fan-village-rockefeller-ny",
    type: "fan_festival",
    name: "Fan Village Rockefeller Center — FIFA x Telemundo",
    datesOpen: "6 jul – 19 jul 2026",
    entry: "Ticketada ($12.50)",
    notes: "Asociación FIFA y Telemundo. La pista de patinaje se convierte en campo de fútbol con pantallas gigantes.",
  },
  // Toronto viejo → desactivar (reemplazado por canada-toronto)
  {
    id: "fan-festival-toronto",
    active: false,
  },
  // Vancouver viejo → desactivar (reemplazado por canada-vancouver)
  {
    id: "fan-festival-vancouver",
    active: false,
  },
  // Guadalajara → nota actualizada con Zapopan confirmado
  {
    id: "fan-festival-guadalajara",
    notes: "Plaza de la Liberación. 39 días, 104 partidos. Acceso libre y gratuito. Fan Zones adicionales en Zapopan confirmados.",
  },
];

export async function patchFanZones(): Promise<void> {
  for (const { id, ...data } of PATCHES) {
    await setDoc(
      doc(db, "wc2026_fanzones", id),
      { ...data, updatedAt: serverTimestamp() },
      { merge: true }
    );
    console.log(`Patched fan zone: ${id}`);
  }
  console.log(`patchFanZones complete — ${PATCHES.length} documents patched.`);
}
