// src/lib/firestore/seedFanZones.ts
// Llamar UNA SOLA VEZ desde el admin panel para poblar wc2026_fanzones.
// Usa setDoc con IDs explícitos para que sea idempotente (safe to re-run).
import { db } from "../firebase";
import { doc, setDoc, serverTimestamp } from "firebase/firestore";
import type { FanZone } from "./fanzones";

type SeedRow = Omit<FanZone, "id" | "updatedAt" | "food" | "alcohol" | "amenities"> & {
  food?: string | null;
  alcohol?: boolean | null;
  amenities?: string | null;
};

const FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── USA — FIFA FAN FESTIVALS OFICIALES ───────────────────────────────────
  {
    id: "fan-festival-philadelphia",
    type: "fan_festival",
    name: "FIFA Fan Festival Philadelphia",
    city: "Philadelphia",
    country: "usa",
    venue: "Lemon Hill, Fairmount Park",
    address: "1 Lemon Hill Drive, Philadelphia, PA 19130",
    lat: 40.7684,
    lng: -75.1838,
    entry: "Gratuita, requiere registro anticipado",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://phillyfwc26.com/fifa-fan-fest",
    registrationUrl: "https://phillyfwc26.com/fifa-fan-fest",
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-dallas",
    type: "fan_festival",
    name: "FIFA Fan Festival Dallas",
    city: "Dallas",
    country: "usa",
    venue: "Fair Park",
    address: "3809 Grand Ave, Dallas, TX 75210",
    lat: 32.7802,
    lng: -96.7492,
    entry: "Gratuita, sin registro requerido",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://www.dallasfwc26.com/our-venues/fan-festival/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-houston",
    type: "fan_festival",
    name: "FIFA Fan Festival Houston",
    city: "Houston",
    country: "usa",
    venue: "East Downtown (EaDo), cerca de Shell Energy Stadium",
    address: "East Downtown, Houston, TX 77003",
    lat: 29.7523,
    lng: -95.3518,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026 (34 días)",
    officialUrl: "https://www.fwc26houston.com/fifafanfestivalhou",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-kansas-city",
    type: "fan_festival",
    name: "FIFA Fan Festival Kansas City",
    city: "Kansas City",
    country: "usa",
    venue: "National WWI Museum and Memorial",
    address: "2 Memorial Dr, Kansas City, MO 64108",
    lat: 39.0997,
    lng: -94.5786,
    entry: "Gratuita, requiere pase digital anticipado",
    datesOpen: "11 jun – 13 jul 2026 (18 días)",
    officialUrl: "https://kansascityfwc26.com/fifa-fan-festival/",
    registrationUrl: "https://kansascityfwc26.com/fifa-fan-festival/",
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-miami",
    type: "fan_festival",
    name: "FIFA Fan Festival Miami",
    city: "Miami",
    country: "usa",
    venue: "Bayfront Park",
    address: "301 Biscayne Blvd, Miami, FL 33132",
    lat: 25.7751,
    lng: -80.1839,
    entry: "Gratuita",
    datesOpen: "13 jun – 5 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-atlanta",
    type: "fan_festival",
    name: "FIFA Fan Festival Atlanta",
    city: "Atlanta",
    country: "usa",
    venue: "Centennial Olympic Park",
    address: "235 Park Ave SW, Atlanta, GA 30313",
    lat: 33.7601,
    lng: -84.3922,
    entry: "Gratuita",
    datesOpen: "20 días durante el torneo",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-boston",
    type: "fan_festival",
    name: "FIFA Fan Festival Boston",
    city: "Boston",
    country: "usa",
    venue: "City Hall Plaza",
    address: "City Hall Plaza, Boston, MA 02201",
    lat: 42.3601,
    lng: -71.0589,
    entry: "TBC",
    datesOpen: "Hasta 16 días en jun 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-los-angeles",
    type: "fan_festival",
    name: "FIFA Fan Festival Los Angeles",
    city: "Los Angeles",
    country: "usa",
    venue: "LA Memorial Coliseum",
    address: "3911 S Figueroa St, Los Angeles, CA 90037",
    lat: 34.0141,
    lng: -118.2879,
    entry: "Desde $10 (niños 12 y menor gratis)",
    datesOpen: "11 jun – 14 jun 2026",
    officialUrl: "https://losangelesfwc26.com/fifa-fan-festival-los-angeles/",
    registrationUrl: "https://losangelesfwc26.com/fifa-fan-festival-los-angeles/",
    notes: null,
    active: true,
  },

  // ─── USA — FAN ZONES BAY AREA ─────────────────────────────────────────────
  {
    id: "fan-zone-thrive-city-sf",
    type: "fan_zone",
    name: "Thrive City Fan Zone",
    city: "San Francisco",
    country: "usa",
    venue: "Thrive City, Chase Center",
    address: "1 Warriors Way, San Francisco, CA 94158",
    lat: 37.7679,
    lng: -122.3874,
    entry: "Gratuita",
    datesOpen: "18 jun 2026 (México vs Corea del Sur)",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-zone-san-pedro-square-sj",
    type: "fan_zone",
    name: "San Pedro Square Market Fan Zone",
    city: "San Jose",
    country: "usa",
    venue: "San Pedro Square Market",
    address: "87 N San Pedro St, San Jose, CA 95110",
    lat: 37.3363,
    lng: -121.895,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Hub principal del Bay Area. Venues adicionales por confirmar.",
    active: true,
  },

  // ─── USA — FAN ZONES NEW YORK ─────────────────────────────────────────────
  {
    id: "fan-zone-queens-ny",
    type: "fan_zone",
    name: "Fan Zone Queens",
    city: "New York",
    country: "usa",
    venue: "Louis Armstrong Stadium, USTA Billie Jean King Center",
    address: "124-02 Roosevelt Ave, Corona, NY 11368",
    lat: 40.7498,
    lng: -73.8458,
    entry: "Gratuita, requiere ticket anticipado (Live Nation)",
    datesOpen: "17 jun – 28 jun 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: "https://nynjfwc26.com/fan-zones/",
    notes: null,
    active: true,
  },
  {
    id: "fan-village-rockefeller-ny",
    type: "fan_zone",
    name: "Fan Village Rockefeller Center",
    city: "New York",
    country: "usa",
    venue: "Rockefeller Center",
    address: "45 Rockefeller Plaza, New York, NY 10111",
    lat: 40.7587,
    lng: -73.9787,
    entry: "Gratuita",
    datesOpen: "4 jul – 19 jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-hub-harrison-nj",
    type: "fan_zone",
    name: "NYNJ Jersey Fan Hub",
    city: "Harrison, NJ",
    country: "usa",
    venue: "Sports Illustrated Stadium",
    address: "1 Sports Dr, Harrison, NJ 07029",
    lat: 40.7417,
    lng: -74.1554,
    entry: "Gratuita",
    datesOpen: "Fechas selectas Jun–Jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── CANADÁ ───────────────────────────────────────────────────────────────
  {
    id: "fan-festival-toronto",
    type: "fan_festival",
    name: "FIFA Fan Festival Toronto",
    city: "Toronto",
    country: "canada",
    venue: "Fort York National Historic Site",
    address: "250 Fort York Blvd, Toronto, ON M5V 3K9",
    lat: 43.6359,
    lng: -79.4005,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-vancouver",
    type: "fan_festival",
    name: "FIFA Fan Festival Vancouver",
    city: "Vancouver",
    country: "canada",
    venue: "Hastings Park",
    address: "Hastings Park, Vancouver, BC V5K 0A1",
    lat: 49.2827,
    lng: -123.0348,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── MÉXICO ───────────────────────────────────────────────────────────────
  {
    id: "fan-festival-cdmx",
    type: "fan_festival",
    name: "FIFA Fan Festival Ciudad de México",
    city: "Ciudad de México",
    country: "mexico",
    venue: "El Zócalo (Plaza de la Constitución)",
    address: "Plaza de la Constitución S/N, Centro Histórico, CDMX",
    lat: 19.4326,
    lng: -99.1332,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Espacios adicionales en las alcaldías de CDMX",
    active: true,
  },
  {
    id: "fan-festival-monterrey",
    type: "fan_festival",
    name: "FIFA Fan Festival Monterrey",
    city: "Monterrey",
    country: "mexico",
    venue: "Parque Fundidora",
    address: "Av. Fundidora 501, Obrera, Monterrey, N.L.",
    lat: 25.6777,
    lng: -100.285,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://www.fwc26monterrey.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-festival-guadalajara",
    type: "fan_festival",
    name: "FIFA Fan Festival Guadalajara",
    city: "Guadalajara",
    country: "mexico",
    venue: "Plaza Liberación",
    address: "C. Pedro Loza 27A, Zona Centro, 44100 Guadalajara, Jal.",
    lat: 20.6597,
    lng: -103.3496,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Espacios alternos en Zapopan: Parque Rojo, Plaza Las Américas",
    active: true,
  },
];

export async function seedFanZones(): Promise<void> {
  for (const { id, ...data } of FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedFanZones complete — ${FAN_ZONES.length} documents written.`);
}

// ─── NUEVOS FAN ZONES — Abril 2026 ────────────────────────────────────────────
// Solo agregar. No sobreescribe los documentos existentes (IDs diferentes).
const NEW_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── NUEVA YORK — Fan Zones adicionales ─────────────────────────────────────
  {
    id: "ny-brooklyn",
    type: "fan_zone",
    name: "Fan Zone Brooklyn",
    city: "Brooklyn",
    country: "usa",
    venue: "Brooklyn Bridge Park",
    address: "334 Furman St, Brooklyn, NY 11201",
    lat: 40.7022,
    lng: -73.9965,
    entry: "Gratuita",
    datesOpen: "13 jun – 19 jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "ny-staten-island",
    type: "fan_zone",
    name: "Fan Zone Staten Island",
    city: "Staten Island",
    country: "usa",
    venue: "FerryHawks SIUH Community Park",
    address: "2401 Richmond Ave, Staten Island, NY 10314",
    lat: 40.6469,
    lng: -74.0768,
    entry: "Gratuita",
    datesOpen: "29 jun – 2 jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "ny-bronx",
    type: "fan_zone",
    name: "Fan Zone El Bronx",
    city: "Bronx",
    country: "usa",
    venue: "Bronx Terminal Market",
    address: "610 Exterior St, Bronx, NY 10451",
    lat: 40.8236,
    lng: -73.9286,
    entry: "Gratuita",
    datesOpen: "13–14 jun 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "nj-jersey-city",
    type: "fan_zone",
    name: "Jersey Fan Hub",
    city: "Jersey City",
    country: "usa",
    venue: "Liberty State Park",
    address: "1 Audrey Zapp Dr, Jersey City, NJ 07305",
    lat: 40.7042,
    lng: -74.0531,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: "https://nynjfwc26.com/fan-zones/",
    registrationUrl: null,
    notes: "Cancelado oficialmente en febrero 2026.",
    active: false,
  },

  // ─── LOS ÁNGELES — Fan Zones adicionales ────────────────────────────────────
  {
    id: "la-union-station",
    type: "fan_zone",
    name: "Fan Zone Union Station",
    city: "Los Angeles",
    country: "usa",
    venue: "Union Station",
    address: "800 N Alameda St, Los Angeles, CA 90012",
    lat: 34.0562,
    lng: -118.2365,
    entry: "Gratuita",
    datesOpen: "25–28 jun 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-hansen-dam",
    type: "fan_zone",
    name: "Fan Zone Hansen Dam",
    city: "Lake View Terrace",
    country: "usa",
    venue: "Hansen Dam Recreation Area",
    address: "11770 Foothill Blvd, Lake View Terrace, CA 91342",
    lat: 34.2709,
    lng: -118.3842,
    entry: "Gratuita",
    datesOpen: "2–5 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-magic-johnson-park",
    type: "fan_zone",
    name: "Fan Zone Earvin Magic Johnson Park",
    city: "Willowbrook",
    country: "usa",
    venue: "Earvin Magic Johnson Park",
    address: "905 E El Segundo Blvd, Willowbrook, CA 90222",
    lat: 33.9163,
    lng: -118.2581,
    entry: "Gratuita",
    datesOpen: "4–5 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-whittier-narrows",
    type: "fan_zone",
    name: "Fan Zone Whittier Narrows",
    city: "South El Monte",
    country: "usa",
    venue: "Whittier Narrows Recreation Area",
    address: "750 S Santa Anita Ave, South El Monte, CA 91733",
    lat: 34.0372,
    lng: -118.0669,
    entry: "Gratuita",
    datesOpen: "9–11 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-fairplex",
    type: "fan_zone",
    name: "Fan Zone Fairplex Pomona",
    city: "Pomona",
    country: "usa",
    venue: "Fairplex",
    address: "1101 W McKinley Ave, Pomona, CA 91768",
    lat: 34.0850,
    lng: -117.7667,
    entry: "Gratuita",
    datesOpen: "14–15 y 18–19 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-west-harbor",
    type: "fan_zone",
    name: "Fan Zone West Harbor Waterfront",
    city: "San Pedro",
    country: "usa",
    venue: "West Harbor Waterfront",
    address: "1200 Nagoya Way, San Pedro, CA 90731",
    lat: 33.7401,
    lng: -118.2783,
    entry: "Gratuita",
    datesOpen: "14–15 y 18–19 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "la-burbank",
    type: "fan_zone",
    name: "Fan Zone Downtown Burbank",
    city: "Burbank",
    country: "usa",
    venue: "San Fernando Blvd",
    address: "San Fernando Blvd, Burbank, CA 91502",
    lat: 34.1808,
    lng: -118.3090,
    entry: "Gratuita",
    datesOpen: "18–19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },

  // ─── BAY AREA — Fan Zones adicionales ───────────────────────────────────────
  {
    id: "sf-china-basin",
    type: "fan_zone",
    name: "Fan Zone China Basin Park",
    city: "San Francisco",
    country: "usa",
    venue: "China Basin Park at Mission Rock",
    address: "China Basin Park, San Francisco, CA 94107",
    lat: 37.7751,
    lng: -122.3893,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },
  {
    id: "sf-pier39",
    type: "fan_zone",
    name: "Fan Zone PIER 39",
    city: "San Francisco",
    country: "usa",
    venue: "PIER 39",
    address: "Beach St & The Embarcadero, San Francisco, CA 94133",
    lat: 37.8087,
    lng: -122.4098,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },
  {
    id: "oak-raimondi-park",
    type: "fan_zone",
    name: "Fan Zone Raimondi Park Oakland",
    city: "Oakland",
    country: "usa",
    venue: "Raimondi Park",
    address: "1360 3rd Ave, Oakland, CA 94606",
    lat: 37.7849,
    lng: -122.2477,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },

  // ─── WASHINGTON STATE — Fan Zones del gobierno estatal ───────────────────────
  {
    id: "wa-bellingham",
    type: "fan_zone",
    name: "Fan Zone Bellingham",
    city: "Bellingham",
    country: "usa",
    venue: "Kulshan Brewing Trackside",
    address: "Bellingham, WA",
    lat: 48.7492,
    lng: -122.4842,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Bellingham",
    active: true,
  },
  {
    id: "wa-tacoma",
    type: "fan_zone",
    name: "Fan Zone Tacoma",
    city: "Tacoma",
    country: "usa",
    venue: "Puyallup Tribal Headquarters",
    address: "Tacoma, WA",
    lat: 47.2415,
    lng: -122.4102,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por Puyallup Tribe y ciudad de Tacoma",
    active: true,
  },
  {
    id: "wa-spokane",
    type: "fan_zone",
    name: "Fan Zone Spokane",
    city: "Spokane",
    country: "usa",
    venue: "Riverfront Park — Gesa Pavilion",
    address: "507 N Howard St, Spokane, WA 99201",
    lat: 47.6616,
    lng: -117.4202,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Spokane",
    active: true,
  },
  {
    id: "wa-everett",
    type: "fan_zone",
    name: "Fan Zone Everett",
    city: "Everett",
    country: "usa",
    venue: "Boxcar Park",
    address: "Everett, WA",
    lat: 47.9861,
    lng: -122.2173,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Everett",
    active: true,
  },
  {
    id: "wa-olympia",
    type: "fan_zone",
    name: "Fan Zone Olympia",
    city: "Olympia",
    country: "usa",
    venue: "Port Plaza",
    address: "Olympia, WA",
    lat: 47.0505,
    lng: -122.9067,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por Port of Olympia",
    active: true,
  },
  {
    id: "wa-yakima",
    type: "fan_zone",
    name: "Fan Zone Yakima",
    city: "Yakima",
    country: "usa",
    venue: "Sozo Sports Complex",
    address: "5801 Occidental Rd, Yakima, WA 98903",
    lat: 46.5642,
    lng: -120.5481,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por Yakima Host Committee",
    active: true,
  },
  {
    id: "wa-bremerton",
    type: "fan_zone",
    name: "Fan Zone Bremerton",
    city: "Bremerton",
    country: "usa",
    venue: "Quincy Square",
    address: "Quincy Ave, Bremerton, WA 98337",
    lat: 47.5651,
    lng: -122.6328,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Giant LED screen, 8 zonas únicas, food trucks, beer gardens. Organizado por ciudad de Bremerton.",
    active: true,
  },
  {
    id: "wa-tri-cities",
    type: "fan_zone",
    name: "Fan Zone Tri-Cities",
    city: "Pasco",
    country: "usa",
    venue: "Pasco Sporting Complex",
    address: "6160 Burden Blvd, Pasco, WA 99301",
    lat: 46.2396,
    lng: -119.1006,
    entry: "Gratuita",
    datesOpen: "Jun – Jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Organizado por ciudad de Pasco / Tri-Cities Host Committee.",
    active: true,
  },
  // ─── ADIDAS HOME OF SOCCER ────────────────────────────────────────────────
  {
    id: "adidas-home-soccer-nyc",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Nueva York",
    city: "Nueva York",
    country: "usa",
    venue: "Brooklyn Bridge Park",
    address: "334 Furman St, Brooklyn, NY 11201",
    lat: 40.6961,
    lng: -73.9969,
    entry: "Gratis — Walk-in",
    datesOpen: "13 jun – 19 jul 2026 (12pm–10pm diario)",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: "https://www.adidas.com/us/world-cup",
    notes: "Conciertos: PinkPantheress y Larry June (26 jun). Surprise performance 18 jul. Apariciones: Zinedine Zidane, Kaká, Marcelo, Paul Pogba, Aitana Bonmatí, Trinity Rodman, Jaedyn Shaw y más.",
    food: "Food and beverage curado con beer garden",
    alcohol: true,
    amenities: "25,000 sq ft. Watch parties todos los partidos. Beer garden. Retail Adidas completo (14 kits de federaciones). Panini customization station. AdiCup 3v3 tournament (final 18 jul). Airbnb design experience. Conciertos PinkPantheress y Larry June. Apariciones de leyendas: Zidane, Kaká, Marcelo, Pogba, Aitana Bonmatí, Trinity Rodman. Surprise performance 18 jul. Capacidad 3,500+.",
    active: true,
    status: "active",
  },
  {
    id: "adidas-home-soccer-la",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Los Ángeles",
    city: "Los Ángeles",
    country: "usa",
    venue: "BMO Stadium",
    address: "3939 S Figueroa St, Los Angeles, CA 90037",
    lat: 34.0131,
    lng: -118.2851,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun 2026 (11am–11pm) + más fechas por confirmar",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: "https://www.adidas.com/us/world-cup",
    notes: "Concierto gratis de Peso Pluma con DJ set de Noodles la noche del 11 de junio — día del partido inaugural México vs South Africa.",
    food: "Food vendors en el venue",
    alcohol: true,
    amenities: "Watch party México vs South Africa (12pm). AdiCup 3v3 apertura. Watch party South Korea vs Czechia (7pm). Concierto gratis Peso Pluma + DJ Noodles. Retail Adidas. Más fechas por confirmar.",
    active: true,
    status: "active",
  },
  {
    id: "adidas-home-soccer-toronto",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Toronto",
    city: "Toronto",
    country: "canada",
    venue: "STACKT Market",
    address: "28 Bathurst St, Toronto, ON M5V 0C2",
    lat: 43.6396,
    lng: -79.4025,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: "https://www.adidas.com/us/world-cup",
    notes: "Colaboración exclusiva con A Ma Maniére del 16 jun al 16 jul.",
    food: "Food vendors curados",
    alcohol: true,
    amenities: "Outdoor screenings todos los partidos. Retail Adidas pop-up. Strike Lab: prueba boots Predator vs F50. Special guests. A Ma Maniére collab 16 jun–16 jul. Familiar y gratis.",
    active: true,
    status: "active",
  },
  {
    id: "adidas-home-soccer-houston",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Houston",
    city: "Houston",
    country: "usa",
    venue: "Por confirmar",
    address: "Houston, TX",
    lat: 29.7604,
    lng: -95.3698,
    entry: "Gratis — Walk-in",
    datesOpen: "Fechas selectas — 28 jun confirmado + más por anunciar",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: "https://www.adidas.com/us/world-cup",
    notes: "Sneaker Politics retail activation el 28 jun. AdiCup 3v3 tournament. Más detalles por anunciar.",
    food: null,
    alcohol: null,
    amenities: "AdiCup 3v3. Sneaker Politics retail activation (28 jun). Más detalles por anunciar.",
    active: true,
    status: "coming_soon",
  },
  {
    id: "adidas-home-soccer-atlanta",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Atlanta",
    city: "Atlanta",
    country: "usa",
    venue: "Por confirmar",
    address: "Atlanta, GA",
    lat: 33.7490,
    lng: -84.3880,
    entry: "Gratis — Walk-in",
    datesOpen: "16 jun – 16 jul 2026 (fechas selectas)",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: "https://www.adidas.com/us/world-cup",
    notes: "Colaboración exclusiva con A Ma Maniére del 16 jun al 16 jul. Más detalles por anunciar.",
    food: null,
    alcohol: null,
    amenities: "A Ma Maniére retail integration. Más detalles por anunciar.",
    active: true,
    status: "coming_soon",
  },
  {
    id: "adidas-home-soccer-cdmx",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — CDMX",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — dentro del FIFA Fan Festival Zócalo",
    address: "Plaza de la Constitución, Cuauhtémoc, CDMX",
    lat: 19.4326,
    lng: -99.1332,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: null,
    notes: "Adidas es key sponsor del FIFA Fan Festival CDMX. Activaciones dentro del Zócalo. Detalles por anunciar.",
    food: null,
    alcohol: false,
    amenities: "Activaciones Adidas dentro del Fan Festival del Zócalo. Retail, productos exclusivos y más. Detalles por anunciar.",
    active: true,
    status: "coming_soon",
  },
  {
    id: "adidas-home-soccer-gdl",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Guadalajara",
    city: "Guadalajara",
    country: "mexico",
    venue: "Por confirmar — dentro del FIFA Fan Festival Plaza Liberación",
    address: "Plaza Liberación, Centro Histórico, Guadalajara",
    lat: 20.6597,
    lng: -103.3496,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: null,
    notes: "Adidas es key sponsor del FIFA Fan Festival Guadalajara. Activaciones dentro de Plaza Liberación. Detalles por anunciar.",
    food: null,
    alcohol: true,
    amenities: "Activaciones Adidas dentro del Fan Festival. Retail, productos exclusivos y más. Detalles por anunciar.",
    active: true,
    status: "coming_soon",
  },
  {
    id: "adidas-home-soccer-mty",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Adidas Home of Soccer — Monterrey",
    city: "Monterrey",
    country: "mexico",
    venue: "Por confirmar — dentro del FIFA Fan Festival Parque Fundidora",
    address: "Parque Fundidora, Monterrey, NL",
    lat: 25.6714,
    lng: -100.2836,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://www.adidas.com/us/world-cup",
    registrationUrl: null,
    notes: "Adidas es key sponsor del FIFA Fan Festival Monterrey. Activaciones dentro de Parque Fundidora. Detalles por anunciar.",
    food: null,
    alcohol: true,
    amenities: "Activaciones Adidas dentro del Fan Festival. Retail, productos exclusivos y más. Detalles por anunciar.",
    active: true,
    status: "coming_soon",
  },
];

export async function seedNewFanZones(): Promise<void> {
  for (const { id, ...data } of NEW_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded new fan zone: ${id}`);
  }
  console.log(`seedNewFanZones complete — ${NEW_FAN_ZONES.length} documents written.`);
}

// ─── CDMX + GUADALAJARA — 30 abril 2026 ──────────────────────────────────────
// 9 Festivales Futboleros CDMX (anunciados por Clara Brugada) +
// 4 Fan Zones de Zapopan (gobierno municipal)
const CDMX_GDL_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── CIUDAD DE MÉXICO ────────────────────────────────────────────────────────
  {
    id: "cdmx-chapultepec-cricri",
    type: "fan_zone",
    name: "Festival Futbolero Parque Cri-Cri",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Cri-Cri, Bosque de Chapultepec 3a Sección",
    address: "Bosque de Chapultepec, Miguel Hidalgo, CDMX",
    lat: 19.4180,
    lng: -99.2050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-utopia-meyehualco",
    type: "fan_zone",
    name: "Festival Futbolero Utopía Meyehualco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Utopía Meyehualco",
    address: "Iztapalapa, CDMX",
    lat: 19.3450,
    lng: -99.0420,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-campos-revolucion",
    type: "fan_zone",
    name: "Festival Futbolero Campos Revolución",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Campos Revolución",
    address: "Gustavo A. Madero, CDMX",
    lat: 19.4850,
    lng: -99.1180,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-garibaldi",
    type: "fan_zone",
    name: "Festival Futbolero Plaza Garibaldi",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Plaza Garibaldi",
    address: "Plaza Garibaldi, Cuauhtémoc, CDMX",
    lat: 19.4264,
    lng: -99.1394,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede de Cuauhtémoc. Transmite partidos de México y encuentros destacados. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-deportivo-galeana",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Hermanos Galeana",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Hermanos Galeana",
    address: "Gustavo A. Madero, CDMX",
    lat: 19.4950,
    lng: -99.1050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Transmite partidos de México y encuentros destacados.",
    active: true,
  },
  {
    id: "cdmx-iztapalapa",
    type: "fan_zone",
    name: "Festival Futbolero Iztapalapa",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Iztapalapa",
    address: "Iztapalapa, CDMX",
    lat: 19.3557,
    lng: -99.0554,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-coyoacan",
    type: "fan_zone",
    name: "Festival Futbolero Coyoacán",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Coyoacán",
    address: "Coyoacán, CDMX",
    lat: 19.3467,
    lng: -99.1617,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-tlalpan",
    type: "fan_zone",
    name: "Festival Futbolero Tlalpan",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Tlalpan",
    address: "Tlalpan, CDMX",
    lat: 19.2969,
    lng: -99.1661,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-xochimilco",
    type: "fan_zone",
    name: "Festival Futbolero Xochimilco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Xochimilco",
    address: "Xochimilco, CDMX",
    lat: 19.2571,
    lng: -99.1043,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },

  {
    id: "cdmx-bombilla",
    type: "fan_zone",
    name: "Festival Futbolero Parque La Bombilla",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque La Bombilla",
    address: "Álvaro Obregón, CDMX",
    lat: 19.3556,
    lng: -99.1800,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-tezozomoc",
    type: "fan_zone",
    name: "Festival Futbolero Parque Tezozómoc",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Tezozómoc",
    address: "Azcapotzalco, CDMX",
    lat: 19.4934,
    lng: -99.1756,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-parque-americas",
    type: "fan_zone",
    name: "Festival Futbolero Parque Las Américas",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Las Américas",
    address: "Benito Juárez, CDMX",
    lat: 19.3964,
    lng: -99.1592,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-consolacion",
    type: "fan_zone",
    name: "Festival Futbolero Parque de la Consolación",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque de la Consolación",
    address: "Coyoacán, CDMX",
    lat: 19.3500,
    lng: -99.1650,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-san-mateo-atenco",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo San Mateo Atenco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo San Mateo Atenco",
    address: "Cuajimalpa, CDMX",
    lat: 19.3600,
    lng: -99.2900,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-leandro-valle",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Leandro Valle",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Leandro Valle",
    address: "Iztacalco, CDMX",
    lat: 19.3950,
    lng: -99.1050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-unidad-independencia",
    type: "fan_zone",
    name: "Festival Futbolero Unidad Independencia",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Unidad Independencia",
    address: "La Magdalena Contreras, CDMX",
    lat: 19.3150,
    lng: -99.2050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-tlahuac",
    type: "fan_zone",
    name: "Festival Futbolero Bosque de Tláhuac",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Bosque de Tláhuac",
    address: "Tláhuac, CDMX",
    lat: 19.2750,
    lng: -99.0050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-vivanco",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Vivanco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Vivanco",
    address: "Tlalpan, CDMX",
    lat: 19.2900,
    lng: -99.1600,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-eduardo-molina",
    type: "fan_zone",
    name: "Festival Futbolero Utopía Eduardo Molina",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Utopía Deportivo Eduardo Molina",
    address: "Venustiano Carranza, CDMX",
    lat: 19.4350,
    lng: -99.0850,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },

  // ─── GUADALAJARA / ZAPOPAN ────────────────────────────────────────────────────
  {
    id: "gdl-parque-rojo",
    type: "fan_zone",
    name: "Fan Zone Parque Rojo",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque Rojo",
    address: "Av. Vallarta / Juárez, Zapopan, Jalisco",
    lat: 20.6750,
    lng: -103.3551,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-parque-la-mujer",
    type: "fan_zone",
    name: "Fan Zone Parque La Mujer",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque La Mujer",
    address: "C. Santa Lucía, Zapopan, Jalisco",
    lat: 20.7300,
    lng: -103.4200,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-parque-ninas-ninos",
    type: "fan_zone",
    name: "Fan Zone Parque de Las Niñas y Los Niños",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque de Las Niñas y Los Niños",
    address: "Prolongación Laureles, Zapopan, Jalisco",
    lat: 20.7250,
    lng: -103.3950,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-plaza-las-americas",
    type: "fan_zone",
    name: "Fan Zone Plaza Las Américas",
    city: "Zapopan",
    country: "mexico",
    venue: "Plaza Las Américas",
    address: "Centro de Zapopan, Jalisco",
    lat: 20.7215,
    lng: -103.3925,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 10,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
];

export async function seedCdmxGdlFanZones(): Promise<void> {
  for (const { id, ...data } of CDMX_GDL_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedCdmxGdlFanZones complete — ${CDMX_GDL_FAN_ZONES.length} documents written.`);
}

// ─── CANADÁ — 30 abril 2026 ───────────────────────────────────────────────────
// IDs nuevos con información corregida. Los viejos (fan-festival-toronto,
// fan-festival-vancouver) se desactivan vía patchFanZones().
const CANADA_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  {
    id: "canada-toronto",
    type: "fan_festival",
    name: "FIFA Fan Festival Toronto",
    city: "Toronto",
    country: "canada",
    venue: "Fort York National Historic Site",
    address: "250 Fort York Blvd, Toronto, ON M5V 3K9",
    lat: 43.6359,
    lng: -79.4005,
    entry: "Gratuita",
    datesOpen: "12 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Bajo el lema The World in a City. Destaca la diversidad multicultural de Toronto.",
    active: true,
  },
  {
    id: "canada-vancouver",
    type: "fan_festival",
    name: "FIFA Fan Festival Vancouver",
    city: "Vancouver",
    country: "canada",
    venue: "Hastings Park — PNE Grounds",
    address: "2901 E Hastings St, Vancouver, BC V5K 0A1",
    lat: 49.2827,
    lng: -123.0348,
    entry: "Gratuita (asientos reservados en anfiteatro ticketados)",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Anfiteatro de 10,000 personas. Conciertos: Mötley Crüe y Kx5 (Deadmau5 + Kaskade) en julio.",
    active: true,
  },
];

export async function seedCanadaFanZones(): Promise<void> {
  for (const { id, ...data } of CANADA_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedCanadaFanZones complete — ${CANADA_FAN_ZONES.length} documents written.`);
}

// ─── BAY AREA — nuevas fan zones ─────────────────────────────────────────────
const BAY_AREA_NEW_FAN_ZONES = [
  {
    id: "ba-spark-social-sf",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Spark Social SF",
    city: "San Francisco",
    country: "bay_area",
    venue: "Spark Social SF",
    address: "601 Mission Bay Blvd North, San Francisco, CA 94158",
    lat: 37.7695,
    lng: -122.3927,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sparksocialsf.com/world-cup-watch-parties/",
    registrationUrl: null,
    notes: null,
    food: "Variedad de food vendors locales",
    alcohol: true,
    amenities: "Pantalla gigante al aire libre. Beer garden. Ambiente comunitario. Walk-in sin registro.",
    active: true,
    status: "active",
  },
  {
    id: "ba-treasure-island-gold-bar",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Celebration of Nations — Treasure Island",
    city: "San Francisco",
    country: "bay_area",
    venue: "Gold Bar Whiskey Distillery, Treasure Island",
    address: "1 Avenue of the Palms, Treasure Island, SF 94130",
    lat: 37.8232,
    lng: -122.3707,
    entry: "Gratis con RSVP — Requiere registro en TicketFairy",
    datesOpen: "19 jun – 27 jun 2026 (13 partidos confirmados)",
    officialUrl: "https://ticketfairy.com/tour/celebration-of-nations-waterfront-soccer-watch-parties",
    registrationUrl: "https://ticketfairy.com/tour/celebration-of-nations-waterfront-soccer-watch-parties",
    notes: "Vista al agua. Partidos: USA-Australia, Brazil-Haiti, Germany-Ivory Coast, Ecuador-Germany, Japan-Sweden, Turkey-USA, Norway-France, Uruguay-Spain, Panama-England, Colombia-Portugal, Jordan-Argentina.",
    food: "Opciones locales en el venue",
    alcohol: true,
    amenities: "Pantalla gigante con vista al Bay. Waterfront. Beer garden. 13 partidos confirmados jun 19-27.",
    active: true,
    status: "active",
  },
  {
    id: "ba-walnut-creek-lesher",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Walnut Creek — Lesher Center",
    city: "Walnut Creek",
    country: "bay_area",
    venue: "Hofmann Theater, Lesher Center for the Arts",
    address: "1601 Civic Drive, Walnut Creek, CA 94596",
    lat: 37.9101,
    lng: -122.0652,
    entry: "Gratis — Requiere reserva en LesherArtsCenter.org",
    datesOpen: "13 jun 2026 (12–7 PM)",
    officialUrl: "https://www.lesherartscenter.org",
    registrationUrl: "https://www.lesherartscenter.org",
    notes: "Capacidad limitada a 785 asientos. Partidos: Qatar vs Switzerland 12 PM, Brazil vs Morocco 3 PM.",
    food: null,
    alcohol: true,
    amenities: "Teatro climatizado con 785 asientos. Pantalla gigante. Reserva con anticipación — cupo limitado.",
    active: true,
    status: "active",
  },
  {
    id: "ba-richmond-red-oak",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Richmond — SS Red Oak Victory",
    city: "Richmond",
    country: "bay_area",
    venue: "SS Red Oak Victory Historic Ship",
    address: "1337 Canal Blvd Berth 5, Richmond, CA 94804",
    lat: 37.9137,
    lng: -122.3593,
    entry: "Gratis — Walk-in",
    datesOpen: "12 jun (5–9 PM) y 25 jun (7–9 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Richmond United Soccer Club.",
    food: null,
    alcohol: true,
    amenities: "Barco histórico con vista al agua. 2 fechas: 12 jun y 25 jun. Organizado por Richmond United SC.",
    active: true,
    status: "active",
  },
  {
    id: "ba-richmond-east-brother",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Richmond — East Brother Beer Co",
    city: "Richmond",
    country: "bay_area",
    venue: "East Brother Beer Company",
    address: "1001 Canal Blvd, Richmond, CA 94804",
    lat: 37.9125,
    lng: -122.3601,
    entry: "Gratis — Walk-in",
    datesOpen: "18 jun (5–9 PM) y 24 jun (5:30–9 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Richmond United Soccer Club.",
    food: null,
    alcohol: true,
    amenities: "Brewery con ambiente futbolero. 2 fechas: 18 jun y 24 jun. Organizado por Richmond United SC.",
    active: true,
    status: "active",
  },
  {
    id: "ba-san-carlos-wheeler",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone San Carlos — Wheeler Plaza",
    city: "San Carlos",
    country: "bay_area",
    venue: "Wheeler Parking Plaza",
    address: "616 Laurel St, San Carlos, CA 94070",
    lat: 37.5070,
    lng: -122.2605,
    entry: "Gratis — Walk-in",
    datesOpen: "12 jun (6–8:30 PM) y Final 19 jul (12–7 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por City of San Carlos. Beer y wine disponibles para compra.",
    food: null,
    alcohol: true,
    amenities: "Plaza al aire libre. Beer y wine para compra. 2 fechas: USA vs Paraguay (12 jun) y Final (19 jul).",
    active: true,
    status: "active",
  },
  {
    id: "ba-redwood-city-courthouse",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Redwood City — Courthouse Square",
    city: "Redwood City",
    country: "bay_area",
    venue: "Courthouse Square",
    address: "2200 Broadway, Redwood City, CA 94063",
    lat: 37.4852,
    lng: -122.2364,
    entry: "Gratis — Walk-in",
    datesOpen: "18 jun (6–8:30 PM), 24 jun (6–7 PM), 25 jun (7–9:30 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "3 fechas confirmadas: USA-South Korea, Mexico-Czechia, USA-Türkiye.",
    food: null,
    alcohol: null,
    amenities: "Plaza al aire libre en downtown. 3 partidos confirmados: USA vs South Korea (18 jun), Mexico vs Czechia (24 jun), USA vs Türkiye (25 jun).",
    active: true,
    status: "active",
  },
  {
    id: "ba-san-mateo-central-park",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone San Mateo — Central Park",
    city: "San Mateo",
    country: "bay_area",
    venue: "Central Park",
    address: "50 East 5th Ave, San Mateo, CA 94401",
    lat: 37.5683,
    lng: -122.3228,
    entry: "Gratis — Walk-in",
    datesOpen: "25 jun 2026 (6:45 PM – partido 7 PM) + más fechas por confirmar",
    officialUrl: "https://www.cityofsanmateo.org/4960/Summer-2026-Soccer-Celebrations",
    registrationUrl: null,
    notes: "USA vs Türkiye confirmado 25 jun. Más partidos por anunciar.",
    food: null,
    alcohol: null,
    amenities: "Parque al aire libre. Pantalla gigante. USA vs Türkiye (25 jun). Más fechas por confirmar.",
    active: true,
    status: "active",
  },
  {
    id: "ba-santana-row",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "The Row Cup — Santana Row",
    city: "San Jose",
    country: "bay_area",
    venue: "Santana Row",
    address: "377 Santana Row, San Jose, CA 95128",
    lat: 37.3212,
    lng: -121.9490,
    entry: "Gratis — Walk-in (consumo pagado en restaurantes)",
    datesOpen: "11 jun – 19 jul 2026 (5 semanas)",
    officialUrl: "https://santanarow.com/event/the-row-cup/",
    registrationUrl: null,
    notes: "Watch parties en 15+ restaurantes. FIFA Pop-Up Shop 10 jun – 19 jul.",
    food: "15+ restaurantes: Augustine, Left Bank, Dumpling Time, EMC Seafood, El Jardin, Momosan y más",
    alcohol: true,
    amenities: "FIFA Pop-Up Shop. Live DJs. Happy hours en Vintage Wine Bar. 15+ restaurantes participantes. 5 semanas completas.",
    active: true,
    status: "active",
  },
  {
    id: "ba-morgan-hill",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Morgan Hill — Soccer Kickoff Festival",
    city: "Morgan Hill",
    country: "bay_area",
    venue: "Morgan Hill Outdoor Sports Center",
    address: "16500 Condit Rd, Morgan Hill, CA 95037",
    lat: 37.1305,
    lng: -121.6543,
    entry: "Gratis — Walk-in",
    datesOpen: "13 jun 2026 (9 AM – 5 PM)",
    officialUrl: "https://visitmorganhill.org/event-calendar-detail/soccerfest26",
    registrationUrl: null,
    notes: "Partidos: Qatar vs Switzerland (12 PM) y Brazil vs Morocco (3 PM).",
    food: null,
    alcohol: null,
    amenities: "Outdoor Sports Center. Partidos Qatar-Switzerland y Brazil-Morocco. Organizado por City of Morgan Hill y OV Toros.",
    active: true,
    status: "active",
  },
  {
    id: "ba-milpitas",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Milpitas — Taste of Milpitas",
    city: "Milpitas",
    country: "bay_area",
    venue: "Milpitas Community Center",
    address: "457 E Calaveras Blvd, Milpitas, CA 95035",
    lat: 37.4323,
    lng: -121.8996,
    entry: "Gratis — Walk-in",
    datesOpen: "20 jun 2026 (3–9 PM)",
    officialUrl: "https://mvblfeast.com/taste-of-milpitas/",
    registrationUrl: null,
    notes: "Evento Taste of Milpitas con watch party incluido.",
    food: "Feria gastronómica Taste of Milpitas",
    alcohol: null,
    amenities: "Feria gastronómica + watch party. 20 jun 3-9 PM.",
    active: true,
    status: "active",
  },
  {
    id: "ba-santa-cruz-boardwalk",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Santa Cruz Beach Boardwalk",
    city: "Santa Cruz",
    country: "bay_area",
    venue: "Santa Cruz Beach Boardwalk",
    address: "400 Beach St, Santa Cruz, CA 95060",
    lat: 36.9641,
    lng: -122.0177,
    entry: "Gratis — Walk-in",
    datesOpen: "25 jun 2026 (7–9:30 PM) + más fechas",
    officialUrl: "https://beachboardwalk.com/world-soccer-celebration/",
    registrationUrl: null,
    notes: "USA vs Türkiye confirmado 25 jun. Pantalla LED gigante en la arena.",
    food: "Opciones del Boardwalk",
    alcohol: true,
    amenities: "Pantalla LED gigante. Beer garden frente al Colonnade. Vista al océano. USA vs Türkiye (25 jun).",
    active: true,
    status: "active",
  },
  {
    id: "ba-downtown-oakland",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Downtown Oakland",
    city: "Oakland",
    country: "bay_area",
    venue: "Oakland Marriott City Center",
    address: "1001 Broadway, Oakland, CA 94607",
    lat: 37.8044,
    lng: -122.2711,
    entry: "Gratis — Walk-in",
    datesOpen: "19 jun 2026 (12–3 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: null,
    food: null,
    alcohol: null,
    amenities: "Downtown Oakland. 19 jun 12-3 PM.",
    active: true,
    status: "active",
  },
  {
    id: "ba-jackson-playground-sf",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Jackson Playground SF",
    city: "San Francisco",
    country: "bay_area",
    venue: "Jackson Playground",
    address: "1645 17th St, San Francisco, CA 94107",
    lat: 37.7652,
    lng: -122.3969,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jul 2026 (2–7 PM) — Cuartos de Final",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Cuartos de Final. Organizado por el vecindario.",
    food: null,
    alcohol: null,
    amenities: "Parque al aire libre. Cuartos de Final (11 jul). Organizado por la comunidad.",
    active: true,
    status: "active",
  },
  {
    id: "ba-team-australia-alameda",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Team Australia Open Training — Alameda",
    city: "Alameda",
    country: "bay_area",
    venue: "Oakland Roots Training Facility",
    address: "1220 Harbor Bay Pkwy, Alameda, CA 94502",
    lat: 37.7299,
    lng: -122.2422,
    entry: "Gratis — Requiere registro por sorteo (cierre 28 may 8 AM PT)",
    datesOpen: "3 jun 2026 (3–5:30 PM)",
    officialUrl: "https://bit.ly/ausopentraining",
    registrationUrl: "https://bit.ly/ausopentraining",
    notes: "Sesión abierta del seleccionado de Australia + fotos y autógrafos 5-5:30 PM. Registro por sorteo, ganadores notificados el 29 may.",
    food: null,
    alcohol: null,
    amenities: "Entrenamiento abierto de la selección de Australia. Meet & greet + fotos/autógrafos. Registro por sorteo — cierre 28 mayo.",
    active: true,
    status: "active",
  },
  // ─── PRÓXIMAMENTE — anunciados sin fecha confirmada ──────────────────────
  {
    id: "ba-sausalito",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Sausalito",
    city: "Sausalito",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Sausalito, CA",
    lat: 37.8590,
    lng: -122.4852,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-napa-valley",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Napa Valley",
    city: "Napa",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Napa, CA",
    lat: 38.2975,
    lng: -122.2869,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-santa-rosa",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Santa Rosa",
    city: "Santa Rosa",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Santa Rosa, CA",
    lat: 38.4404,
    lng: -122.7141,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-half-moon-bay",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Half Moon Bay",
    city: "Half Moon Bay",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Half Moon Bay, CA",
    lat: 37.4636,
    lng: -122.4286,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-mountain-view",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Mountain View",
    city: "Mountain View",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Mountain View, CA",
    lat: 37.3861,
    lng: -122.0839,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-burlingame",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Burlingame",
    city: "Burlingame",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Burlingame, CA",
    lat: 37.5842,
    lng: -122.3660,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-sunnyvale",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Cityline Sunnyvale",
    city: "Sunnyvale",
    country: "bay_area",
    venue: "Cityline Sunnyvale",
    address: "Sunnyvale, CA",
    lat: 37.3688,
    lng: -122.0363,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-milpitas-civic",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Milpitas Civic Center Plaza",
    city: "Milpitas",
    country: "bay_area",
    venue: "Civic Center Plaza",
    address: "456 E Calaveras Blvd, Milpitas, CA 95035",
    lat: 37.4320,
    lng: -121.8990,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-santa-cruz-mah",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Santa Cruz — Museum of Art & History",
    city: "Santa Cruz",
    country: "bay_area",
    venue: "Santa Cruz Museum of Art & History",
    address: "705 Front St, Santa Cruz, CA 95060",
    lat: 36.9741,
    lng: -122.0308,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
];

export async function seedBayAreaNewFanZones(): Promise<void> {
  for (const { id, ...data } of BAY_AREA_NEW_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded bay area fan zone: ${id}`);
  }
  console.log(`seedBayAreaNewFanZones complete — ${BAY_AREA_NEW_FAN_ZONES.length} documents written.`);
}

// ─── PARCHES — correcciones sobre documentos ya existentes ───────────────────
// Usa setDoc con merge:true para no sobreescribir campos no mencionados.
type PatchRow = { id: string } & Record<string, unknown>;

const PATCHES: PatchRow[] = [
  // Rockefeller: era fan_zone genérico → es fan_festival FIFA x Telemundo
  {
    id: "fan-village-rockefeller-ny",
    type: "fan_festival",
    name: "Fan Village Rockefeller Center — FIFA x Telemundo",
    datesOpen: "6 jul – 19 jul 2026",
    entry: "Ticketada ($12.50)",
    notes: "Asociación FIFA y Telemundo. La pista de patinaje se convierte en campo de fútbol con pantallas gigantes.",
  },
  // Toronto viejo → desactivar (reemplazado por canada-toronto)
  {
    id: "fan-festival-toronto",
    active: false,
  },
  // Vancouver viejo → desactivar (reemplazado por canada-vancouver)
  {
    id: "fan-festival-vancouver",
    active: false,
  },
  // Guadalajara → nota actualizada con Zapopan confirmado
  {
    id: "fan-festival-guadalajara",
    notes: "Plaza de la Liberación. 39 días, 104 partidos. Acceso libre y gratuito. Fan Zones adicionales en Zapopan confirmados.",
  },
  // Jersey City → cancelado oficialmente en febrero 2026
  {
    id: "nj-jersey-city",
    active: false,
  },
  // Monumento a la Revolución → reemplazado por cdmx-garibaldi (Plaza Garibaldi)
  {
    id: "cdmx-monumento-revolucion",
    active: false,
  },
  // ─── USA — COMPLETO ───────────────────────────────────────────────────────────

  // Fan Festivals oficiales
  {
    id: "fan-festival-philadelphia",
    food: "~80 food trucks del área de Philadelphia",
    alcohol: true,
    amenities: "Múltiples pantallas gigantes en 1 millón de sq ft. DJ y música en vivo. Activaciones FIFA, giveaways, photo ops, juegos interactivos. 39 días completos, el único Fan Festival USA con corrida completa. Capacidad 15,000-20,000/día. Horario 11am-medianoche. Requiere registro en phillyfwc26.com.",
  },
  {
    id: "fan-festival-dallas",
    food: "Food courts locales en Lots 9 y 10 + Pavilion",
    alcohol: true,
    amenities: "Pantallas gigantes en 1 millón de sq ft. Conciertos en vivo en Dos Equis Pavilion (7,000 asientos cubiertos). Mini-pitches, skills contests, zonas de patrocinadores. VIP: GA+ con Starplex Lounge exclusivo. Capacidad 35,000 simultáneos. Producido por C3 Presents (Lollapalooza).",
  },
  {
    id: "fan-festival-houston",
    food: "Opciones locales de Houston: vietnamita, BBQ, italiano",
    alcohol: true,
    amenities: "9 pantallas grandes. Esphera: domo de proyección 360° del Space Center Houston. Torneo 7v7 U11-U18. Misting zones, agua, sombra y médicos on-site. Green Corridor al estadio por METRORail. Gratis, sin registro.",
  },
  {
    id: "fan-festival-kansas-city",
    food: "Restaurantes locales y regionales de Kansas City",
    alcohol: true,
    amenities: "Pantalla principal 4,200 sq ft. Conciertos: The Chainsmokers, Flo Rida, Gabby Barrett, The All-American Rejects, Tech N9ne. KC Heart Gateway entrada 65 ft. Pet-friendly: Dog Days con Purina domingos 14 jun, 21 jun y 5 jul. VIP: Premium Garden Pass $55 / Legacy Lounge $225 all-inclusive. Registro vía FIFA app.",
  },
  {
    id: "fan-festival-miami",
    food: "Gastronomía local de Miami, diversidad culinaria",
    alcohol: true,
    amenities: "Pantallas LED gigantes. Anfiteatro 10,000 personas. Conciertos y DJs internacionales. Instalación interactiva Faces of Fan Festival. Vista a Biscayne Bay. Misting zones, sombra, hidratación. Gratis, 30,000 personas/día.",
  },
  {
    id: "fan-festival-atlanta",
    food: "Food stalls locales y opciones internacionales en Georgia Street",
    alcohol: true,
    amenities: "Pantalla 40 ft en Main Stage. 4 zonas: Main Stage (conciertos), The Playground (activaciones), The Pitch (podcasts AR/VR), Georgia Street (artistas y comida). VIP desde $30 hasta $10,000. Conmemora 30 años Juegos Olímpicos 1996. Registro previo requerido.",
  },
  {
    id: "fan-festival-boston",
    food: "Gastronomía local de Boston curada",
    alcohol: true,
    amenities: "Jumbotron grande. Cultural Showcase con artistas y músicos locales. Apariciones de leyendas FIFA y mascotas oficiales 2026. Área de juegos con balones y habilidades. Solo Group Stage: 12-27 jun (16 días). Capacidad 20,000-25,000. Requiere registro previo.",
  },
  {
    id: "fan-festival-los-angeles",
    food: "Gastronomía inspirada en países participantes. Evento cashless",
    alcohol: true,
    amenities: "Pantallas grandes. DJ y entretenimiento cultural. Road to World Cup Community Day by Amgen. Clinics Grow the Game. VIP: Club Seats $30, Hospitality Tower Lounge $30. Sala sensorial disponible. Solo Opening Weekend: 11-14 jun. Entrada GA $10, niños -12 gratis.",
  },

  // Bay Area
  {
    id: "fan-zone-thrive-city-sf",
    food: "Vendors locales en plaza al aire libre",
    alcohol: true,
    amenities: "Pantalla gigante al aire libre. Activaciones de Kaiser Permanente, Genentech y PG&E. Solo 2 fechas: 12 jun (USA vs Paraguay) y 18 jun (México vs Corea del Sur). Gratis con RSVP.",
  },
  {
    id: "fan-zone-san-pedro-square-sj",
    food: "Menús temáticos por país participante",
    alcohol: true,
    amenities: "2 pantallas gigantes. DJ pre-partido y halftime. Face painting, juegos, giveaways, Soccer Village familiar. Meet & greets con leyendas. VIP Zone para Season Ticket Holders. 39 días completos. Gratis con RSVP.",
  },
  {
    id: "sf-china-basin",
    food: "Restaurantes Mission Rock adyacentes",
    alcohol: true,
    amenities: "Pantallas grandes. Great Lawn, vista a McCovey Cove, Bay Trail. Pet-friendly. Solo match days seleccionados; especiales en semis (14 jul) y Final (19 jul). Gratis.",
  },
  {
    id: "sf-pier39",
    food: "Restaurantes y food stalls del Pier",
    alcohol: true,
    amenities: "Beer garden. Pantallas para partidos selectos. Sea lions, atracciones familiares. Solo USA matches, Round of 16, Cuartos, Semis y Final. Gratis.",
  },
  {
    id: "oak-raimondi-park",
    food: "Food vendors en Prescott Marketplace adyacente",
    alcohol: true,
    amenities: "Pantallas grandes. Organizado por Oakland Roots SC y Oakland Ballers. Solo 1 fecha confirmada: 12 jun 5-9pm (USA vs Paraguay). RSVP vía TicketLeap. Gratis.",
  },

  // Nueva York
  {
    id: "fan-zone-queens-ny",
    food: "Vendors locales representando las 190 nacionalidades de Queens",
    alcohol: true,
    amenities: "Louis Armstrong Stadium como venue principal, capacidad 10,000. DJ y entretenimiento familiar. Juegos interactivos, cultural showcases, merch oficial. VIP disponible. Tren 7 directo desde Times Square. 11-27 jun. Requiere ticket anticipado en Live Nation.",
  },
  {
    id: "fan-village-rockefeller-ny",
    food: "Desde casual bites hasta restaurantes de destino en Rockefeller Center",
    alcohol: true,
    amenities: "La pista de Rockefeller convertida en campo con pantallas gigantes. Champions Garden homenaje a 8 naciones campeonas. Exposición inmersiva Legacies of Champions por Hyundai gratis con timed-entry. LEGO build station. 10% off FIFA Store. Extended hours Finals Week. 4-19 jul. Gratis.",
  },
  {
    id: "fan-hub-harrison-nj",
    food: "Vendors locales del estadio",
    alcohol: true,
    amenities: "Live match viewings. Cultural programming y performances musicales. PATH train desde World Trade Center. Fechas selectas durante el torneo. NOTA: cuesta $10/día, niños -12 gratis con ticket.",
  },
  {
    id: "ny-brooklyn",
    food: "Vendors representando la gastronomía de Brooklyn",
    alcohol: true,
    amenities: "Pantallas con vista al skyline de Manhattan desde el East River. Daily programming, música, waterfront. La corrida más larga de los 5 boroughs: 13 jun - 19 jul (37 días). Gratis con registro.",
  },
  {
    id: "ny-bronx",
    food: null,
    alcohol: true,
    amenities: "Matchday viewings en Bronx Terminal Market. Solo 2 días: 13-14 jun. Gratis con registro.",
  },
  {
    id: "ny-staten-island",
    food: null,
    alcohol: true,
    amenities: "Evening matches con vista al skyline. Acceso vía Staten Island Ferry. 29 jun - 2 jul. Gratis con registro.",
  },
  {
    id: "nj-jersey-city",
    food: null,
    alcohol: false,
    amenities: "CANCELADO — Liberty State Park fue cancelado oficialmente en febrero 2026.",
    active: false,
  },

  // Los Ángeles
  {
    id: "la-union-station",
    food: "Food trucks y vendors locales",
    alcohol: true,
    amenities: "Acceso directo Metro A/B/D/J. Plaza de Cultura y Artes adyacente. 25-28 jun. Gratis.",
  },
  {
    id: "la-hansen-dam",
    food: "Gastronomía global y food vendors",
    alcohol: true,
    amenities: "DJ performances. Beer garden. Classic cars, muralistas, juegos con premios. 2-5 jul. Gratis.",
  },
  {
    id: "la-magic-johnson-park",
    food: "Food trucks y community marketplace",
    alcohol: true,
    amenities: "Family activities, música. Earvin Magic Johnson Park, Willowbrook. 4-5 jul. Gratis.",
  },
  {
    id: "la-whittier-narrows",
    food: "Eats locales del San Gabriel Valley",
    alcohol: true,
    amenities: "Actividades culturales. 9-11 jul. Gratis.",
  },
  {
    id: "la-fairplex",
    food: "Food vendors globales",
    alcohol: true,
    amenities: "Beer gardens. Música en vivo, DJs, performances culturales. Programación familiar. 14-15 jul y 18-19 jul. Gratis.",
  },
  {
    id: "la-west-harbor",
    food: "Vendors en zona waterfront",
    alcohol: true,
    amenities: "Fan zone frente al mar, San Pedro. 14-15 jul y 18-19 jul. Gratis.",
  },
  {
    id: "la-burbank",
    food: "Vendors locales de Burbank",
    alcohol: true,
    amenities: "Día de la Final. VIP experience $300+ con viewing lounge y concierto. 18-19 jul.",
  },

  // Washington State
  {
    id: "wa-bellingham",
    food: "Food trucks y opciones de brewery",
    alcohol: true,
    amenities: "Kulshan Brewing Trackside + The Den + Wild Buffalo. Outdoor block party en 1300 block Commercial St. Gratis.",
  },
  {
    id: "wa-bremerton",
    food: "Food trucks",
    alcohol: true,
    amenities: "Giant LED screen. 8 zonas únicas. Beer gardens. Eventos especiales Juneteenth y 250th anniversary USA. Quincy Square. Gratis.",
  },
  {
    id: "wa-tacoma",
    food: "Food trucks",
    alcohol: true,
    amenities: "Cultural exchange tribal en Puyallup Tribal Headquarters. Gratis.",
  },
  {
    id: "wa-spokane",
    food: "Food trucks",
    alcohol: true,
    amenities: "Gesa Pavilion at Riverfront Park. Gratis.",
  },
  {
    id: "wa-everett",
    food: "Food trucks",
    alcohol: true,
    amenities: "Boxcar Park, Port of Everett. Waterfront fan zone. Gratis.",
  },
  {
    id: "wa-olympia",
    food: "Food trucks",
    alcohol: true,
    amenities: "Waterfront fan zone. Gratis.",
  },
  {
    id: "wa-yakima",
    food: "Food trucks",
    alcohol: true,
    amenities: "Family fun y cultural exchange. Gratis.",
  },
  {
    id: "wa-tri-cities",
    food: "Food trucks",
    alcohol: true,
    amenities: "Pasco Sporting Complex. Gratis.",
  },
  // ─── MÉXICO ───────────────────────────────────────────────────────────────────
  {
    id: "fan-festival-cdmx",
    food: "Gastronomía mexicana desde lo popular hasta lo gourmet, complementada con sabores internacionales",
    alcohol: false,
    amenities: "Pantalla LED de 510 m² — la más grande del torneo a nivel mundial. Conciertos en vivo y DJs. Experiencia inmersiva El Juego Eterno. Canchas de futbol abiertas. Tienda oficial FIFA. Ceremonia inaugural 11 jun con Alejandro Fernández, Belinda, J Balvin, Maná, Lila Downs, Los Ángeles Azules y más. 39 días completos, 104 partidos. Capacidad 55,000-60,000/día. Gratis SIN registro previo. Zona VIP estilo F1 con bar completo (única excepción al policy sin alcohol).",
  },
  {
    id: "fan-festival-monterrey",
    food: "Gastronomía local de Monterrey, zonas de convivencia",
    alcohol: true,
    amenities: "Pantallas gigantes. 20 artistas en vivo: Chayanne (13 jun), Enrique Iglesias, Imagine Dragons, Grupo Firme, Leyenda (11 jun), Parranda (12 jun), Caballo Dorado (14 jun), más rock, regional mexicano, cumbia, ska y electrónica. VIP pagado con bar y mejor vista al escenario (Ticketmaster). Acceso general gratis sin registro, sujeto a cupo por orden de llegada. 39 días.",
  },
  {
    id: "fan-festival-guadalajara",
    food: "Corredor gastronómico en Plaza de Armas: birria, tortas ahogadas, jericallas y sabores tradicionales de Jalisco",
    alcohol: true,
    amenities: "5 pantallas gigantes para los 104 partidos. Concepto La Fiesta más Mexicana. Talleres artísticos en Teatro Degollado. Exhibiciones deportivas familiares. Tren Ligero Línea 3 directo. 4,000 voluntarios. Capacidad 40,000 simultáneos. Gratis sin registro. 39 días.",
  },
  {
    id: "cdmx-chapultepec-cricri",
    food: "Feria gastronómica de pueblos originarios y productos de chinampas",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol abiertas. Concurso de penales y dominadas. Exposiciones escultóricas: ajolotes intervenidos y alebrijes. Programación de cine, animación y baile familiar. Zona infantil. Transmite los 104 partidos, 39 días completos. Gratis sin alcohol.",
  },
  {
    id: "cdmx-utopia-meyehualco",
    food: "Feria gastronómica de pueblos originarios",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol abiertas. Sonideros, batucadas, comparsas. Zona infantil. Transmite los 104 partidos, 39 días completos. Gratis sin alcohol.",
  },
  {
    id: "cdmx-campos-revolucion",
    food: "Feria gastronómica local",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol abiertas. Música popular y sonideros. Zona infantil. Transmite los 104 partidos, 39 días completos. Gratis sin alcohol.",
  },
  {
    id: "cdmx-garibaldi",
    food: "Gastronomía local de Cuauhtémoc",
    alcohol: false,
    amenities: "Pantalla gigante. Plaza Garibaldi. Música popular, mariachis. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-deportivo-galeana",
    food: "Feria gastronómica local",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-iztapalapa",
    food: "Feria gastronómica de Iztapalapa",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Ubicación exacta por confirmar. Gratis sin alcohol.",
  },
  {
    id: "cdmx-coyoacan",
    food: "Gastronomía local de Coyoacán",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Ubicación exacta por confirmar. Gratis sin alcohol.",
  },
  {
    id: "cdmx-tlalpan",
    food: "Gastronomía local de Tlalpan",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Ubicación exacta por confirmar. Gratis sin alcohol.",
  },
  {
    id: "cdmx-xochimilco",
    food: "Gastronomía de Xochimilco, productos de chinampas",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-bombilla",
    food: "Feria gastronómica local de Álvaro Obregón",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-tezozomoc",
    food: "Feria gastronómica local de Azcapotzalco",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-parque-americas",
    food: "Gastronomía local de Benito Juárez",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-consolacion",
    food: "Gastronomía local de Coyoacán",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-san-mateo-atenco",
    food: "Gastronomía local de Cuajimalpa",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-leandro-valle",
    food: "Gastronomía local de Iztacalco",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-unidad-independencia",
    food: "Gastronomía local de La Magdalena Contreras",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-tlahuac",
    food: "Gastronomía local de Tláhuac",
    alcohol: false,
    amenities: "Pantalla gigante. Bosque de Tláhuac. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-vivanco",
    food: "Gastronomía local de Tlalpan",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-eduardo-molina",
    food: "Gastronomía local de Venustiano Carranza",
    alcohol: false,
    amenities: "Pantalla gigante. Utopía Deportivo Eduardo Molina. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "gdl-parque-rojo",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Actividades familiares. Frente a Basílica de Zapopan. Capacidad ~8,000. Gratis. 39 días.",
  },
  {
    id: "gdl-parque-la-mujer",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Programación cultural. Capacidad ~8,000. Gratis. 39 días.",
  },
  {
    id: "gdl-parque-ninas-ninos",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Actividades familiares. Capacidad ~8,000. Gratis. 39 días.",
  },
  {
    id: "gdl-plaza-las-americas",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Estacionamiento subterráneo disponible. Capacidad ~10,000. Gratis. 39 días.",
  },
  // ─── CANADÁ ───────────────────────────────────────────────────────────────────
  {
    id: "canada-toronto",
    food: "Street Eats con 30+ vendors sirviendo sabores globales y pastries canadienses",
    alcohol: true,
    amenities: "Múltiples pantallas en Fort York y The Bentway. Conciertos: Alessia Cara, Bedouin Soundclash, Big Wreck, Walk off the Earth, Kardinal Offishall. Ontario Pitch (mini-golf temático). LEGO build station. Tkaronto Market (espacio de vendors indígenas). FIFA Store. VIP: Casamigos Clubhouse (lounge doble piso climatizado), Garden Pavilion y Pitchside Terrace — desde $100 hasta $300. 22 event days. GA gratis pero requiere reservación Ticketmaster (se agota rápido). Sin estacionamiento general, solo transporte público.",
  },
  {
    id: "canada-vancouver",
    food: "Gastronomía elevada con opciones locales de Vancouver",
    alcohol: true,
    amenities: "Anfiteatro PNE con capacidad 10,000. 60+ conciertos gratuitos en Park Stage. Conciertos pagados en anfiteatro: Mötley Crüe (12 jul), KX5 — Kaskade + Deadmau5 (17 jul). Conciertos gratis destacados: Chromeo (18 jun), Metric + Ozomatli (26 jun), Simple Plan (2 jul), Ziggy Marley (3 jul), Thievery Corporation (5 jul), Arkells (7 jul), Kaytranada en la Final (19 jul). Pantallas en todo el site para los 46 partidos. Activaciones FIFA. 28 días continuos. GA gratis, asientos anfiteatro desde $44 lawn / $115 reserved. Expo Line a 29th Avenue Station.",
  },
  {
    id: "champions-splash-thrive",
    food: "Menú completo sports bar 30,000 sq ft",
    alcohol: true,
    amenities: "Mega-screen 1,400 sq ft + pantallas adicionales. DJ pre y post partido. Soccer simulators, foosball, shuffleboard. Copa para foto. Gratis con RSVP.",
  },

  // ─── PRECIOS CORREGIDOS ───
  { id: "fan-festival-los-angeles", entry: "Desde $10 GA / $30 VIP — Requiere ticket en Ticketmaster" },
  { id: "fan-hub-harrison-nj", entry: "Desde $10/día — Requiere ticket en SI Tickets" },
  { id: "la-burbank", entry: "VIP desde $300 — Requiere ticket (Final 18-19 jul)" },
  { id: "fan-festival-kansas-city", entry: "Gratis GA con registro · VIP $55 Garden Pass / $225 Legacy Lounge" },
  { id: "fan-festival-atlanta", entry: "Gratis GA con registro · VIP desde $45 hasta $325" },
  { id: "canada-toronto", entry: "Gratis GA con registro en Ticketmaster (agotado) · VIP desde $122 CAD" },
  { id: "canada-vancouver", entry: "Gratis · Conciertos premium desde $44 CAD en anfiteatro" },
  { id: "fan-festival-monterrey", entry: "Gratis GA walk-in · VIP conciertos desde $850 MXN en Ticketmaster" },

  // ─── REGISTRATION URLS ───
  // USA — Fan Festivals oficiales
  { id: "fan-festival-philadelphia", officialUrl: "https://phillyfwc26.com/fifa-fan-fest", registrationUrl: "https://phillyfwc26.com/fifa-fan-fest" },
  { id: "fan-festival-dallas", officialUrl: "https://www.dallasfwc26.com/our-venues/fan-festival/", registrationUrl: "https://www.dallasfwc26.com/our-venues/fan-festival/" },
  { id: "fan-festival-houston", officialUrl: "https://www.fwc26houston.com/fifafanfestivalhou", registrationUrl: "https://www.fwc26houston.com/fifafanfestivalhou" },
  { id: "fan-festival-kansas-city", officialUrl: "https://kansascityfwc26.com/fifa-fan-festival/", registrationUrl: "https://kansascityfwc26.com/fifa-fan-festival/" },
  { id: "fan-festival-miami", officialUrl: "https://miamifwc26.com/fan-festival/", registrationUrl: "https://miamifwc26.com/fan-festival/" },
  { id: "fan-festival-atlanta", officialUrl: "https://atlantafwc26.com/fan-fest/tickets/", registrationUrl: "https://atlantafwc26.com/fan-fest/tickets/" },
  { id: "fan-festival-boston", officialUrl: "https://bostonfwc26.com/fifa-fan-festival/", registrationUrl: "https://bostonfwc26.com/fifa-fan-festival/" },
  { id: "fan-festival-los-angeles", officialUrl: "https://losangelesfwc26.com/fifa-fan-festival-los-angeles/", registrationUrl: "https://www.ticketmaster.com/fifa-fan-festival-los-angeles-tickets/artist/4256617" },

  // USA — Bay Area
  { id: "fan-zone-thrive-city-sf", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "fan-zone-san-pedro-square-sj", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "champions-splash-thrive", officialUrl: "https://www.eventbrite.com/o/kickit365-events-6545084109", registrationUrl: "https://www.eventbrite.com/o/kickit365-events-6545084109" },
  { id: "sf-china-basin", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "sf-pier39", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "oak-raimondi-park", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://events.ticketleap.com/tickets/oaklandroots/raimondi-world-cup-watch-party-usa-vs-paraguay" },

  // USA — Nueva York
  { id: "fan-zone-queens-ny", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },
  { id: "fan-village-rockefeller-ny", officialUrl: "https://www.rockefellercenter.com/events/world-cup-2026", registrationUrl: "https://www.rockefellercenter.com/events/world-cup-2026" },
  { id: "fan-hub-harrison-nj", officialUrl: "https://www.sportsillustratedstadium.com/fan-hub", registrationUrl: "https://www.sportsillustratedstadium.com/fan-hub" },
  { id: "ny-brooklyn", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },
  { id: "ny-bronx", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },
  { id: "ny-staten-island", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },

  // USA — Los Ángeles Fan Zones
  { id: "la-union-station", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://fan-zone-26-at-union-station.eventbrite.com/" },
  { id: "la-hansen-dam", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.fanzonehdl.com/e/hansen-dam-lake-fan-zone" },
  { id: "la-magic-johnson-park", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.eventbrite.com/e/los-angeles-world-cup-26-fan-zone-at-la-countys-magic-johnson-park-tickets-1985958563524" },
  { id: "la-whittier-narrows", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.eventbrite.com/e/los-angeles-world-cup-26-fan-zone-at-los-angeles-county-whittier-narrows-tickets-1985936648977" },
  { id: "la-fairplex", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.discoverlosangeles.com/event/2026/07/14/los-angeles-world-cup-26-fan-zone-at-fairplex" },
  { id: "la-west-harbor", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://tickets.westharborla.com/" },
  { id: "la-burbank", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://tickets.cbfproductions.com/e/los-angeles-world-cup-26-fan-zone-downtown-burbank" },

  // Canadá
  { id: "canada-toronto", officialUrl: "https://torontofwc26.ca/FIFAFanFestival", registrationUrl: "https://www.ticketmaster.ca/fifa-fan-festival-toronto-tickets/artist/4331999" },
  { id: "canada-vancouver", officialUrl: "https://www.vancouverfwc26.ca/fifa-fan-festival", registrationUrl: "https://www.vancouverfwc26.ca/fifa-fan-festival" },

  // ─── BAY AREA COUNTRY UPDATE ───
  { id: "fan-zone-thrive-city-sf", country: "bay_area" },
  { id: "fan-zone-san-pedro-square-sj", country: "bay_area" },
  { id: "sf-china-basin", country: "bay_area" },
  { id: "sf-pier39", country: "bay_area" },
  { id: "oak-raimondi-park", country: "bay_area" },
  { id: "champions-splash-thrive", country: "bay_area" },

  // México
  { id: "fan-festival-cdmx", officialUrl: "https://mexicocityfwc26.com.mx/fifa-fan-festival-cdmx", registrationUrl: null },
  { id: "fan-festival-guadalajara", officialUrl: "https://gdl2026.com", registrationUrl: null },
  { id: "fan-festival-monterrey", officialUrl: "https://www.fwc26monterrey.com", registrationUrl: "https://www.ticketmaster.com.mx/fifa-fan-festival-monterrey-boletos/artist/4444364" },
];

export async function patchFanZones(): Promise<void> {
  for (const { id, ...data } of PATCHES) {
    await setDoc(
      doc(db, "wc2026_fanzones", id),
      { ...data, updatedAt: serverTimestamp() },
      { merge: true }
    );
    console.log(`Patched fan zone: ${id}`);
  }
  console.log(`patchFanZones complete — ${PATCHES.length} documents patched.`);
}
