// src/lib/firestore/seedFanZones.ts
// Llamar UNA SOLA VEZ desde el admin panel para poblar wc2026_fanzones.
// Usa setDoc con IDs explícitos para que sea idempotente (safe to re-run).
import { db } from "../firebase";
import { doc, setDoc, serverTimestamp, deleteDoc, getDocs, collection } from "firebase/firestore";
import type { FanZone } from "./fanzones";

type SeedRow = Omit<FanZone, "id" | "updatedAt" | "food" | "alcohol" | "amenities"> & {
  food?: string | null;
  alcohol?: boolean | null;
  amenities?: string | null;
};

const FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── USA — FAN ZONES BAY AREA ─────────────────────────────────────────────
  {
    id: "fan-zone-thrive-city-sf",
    type: "fan_zone",
    name: "Thrive City Fan Zone",
    city: "San Francisco",
    country: "usa",
    venue: "Thrive City, Chase Center",
    address: "1 Warriors Way, San Francisco, CA 94158",
    lat: 37.7679,
    lng: -122.3874,
    entry: "Gratuita",
    datesOpen: "18 jun 2026 (México vs Corea del Sur)",
    officialUrl: null,
    registrationUrl: null,
    notes: null,
    active: true,
  },
  {
    id: "fan-zone-san-pedro-square-sj",
    type: "fan_zone",
    name: "San Pedro Square Market Fan Zone",
    city: "San Jose",
    country: "usa",
    venue: "San Pedro Square Market",
    address: "87 N San Pedro St, San Jose, CA 95110",
    lat: 37.3363,
    lng: -121.895,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Hub principal del Bay Area. Venues adicionales por confirmar.",
    active: true,
  },

];

export async function seedFanZones(): Promise<void> {
  for (const { id, ...data } of FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedFanZones complete — ${FAN_ZONES.length} documents written.`);
}

// ─── NUEVOS FAN ZONES — Abril 2026 ────────────────────────────────────────────
// Solo agregar. No sobreescribe los documentos existentes (IDs diferentes).
const NEW_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── BAY AREA — Fan Zones adicionales ───────────────────────────────────────
  {
    id: "sf-china-basin",
    type: "fan_zone",
    name: "Fan Zone China Basin Park",
    city: "San Francisco",
    country: "usa",
    venue: "China Basin Park at Mission Rock",
    address: "China Basin Park, San Francisco, CA 94107",
    lat: 37.7751,
    lng: -122.3893,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },
  {
    id: "sf-pier39",
    type: "fan_zone",
    name: "Fan Zone PIER 39",
    city: "San Francisco",
    country: "usa",
    venue: "PIER 39",
    address: "Beach St & The Embarcadero, San Francisco, CA 94133",
    lat: 37.8087,
    lng: -122.4098,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },
  {
    id: "oak-raimondi-park",
    type: "fan_zone",
    name: "Fan Zone Raimondi Park Oakland",
    city: "Oakland",
    country: "usa",
    venue: "Raimondi Park",
    address: "1360 3rd Ave, Oakland, CA 94606",
    lat: 37.7849,
    lng: -122.2477,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Bay Area Host Committee",
    active: true,
  },

];

export async function seedNewFanZones(): Promise<void> {
  for (const { id, ...data } of NEW_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded new fan zone: ${id}`);
  }
  console.log(`seedNewFanZones complete — ${NEW_FAN_ZONES.length} documents written.`);
}

// ─── CDMX + GUADALAJARA — 30 abril 2026 ──────────────────────────────────────
// 9 Festivales Futboleros CDMX (anunciados por Clara Brugada) +
// 4 Fan Zones de Zapopan (gobierno municipal)
const CDMX_GDL_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  // ─── CIUDAD DE MÉXICO ────────────────────────────────────────────────────────
  {
    id: "cdmx-chapultepec-cricri",
    type: "fan_zone",
    name: "Festival Futbolero Parque Cri-Cri",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Cri-Cri, Bosque de Chapultepec 3a Sección",
    address: "Bosque de Chapultepec, Miguel Hidalgo, CDMX",
    lat: 19.4180,
    lng: -99.2050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-utopia-meyehualco",
    type: "fan_zone",
    name: "Festival Futbolero Utopía Meyehualco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Utopía Meyehualco",
    address: "Iztapalapa, CDMX",
    lat: 19.3450,
    lng: -99.0420,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-campos-revolucion",
    type: "fan_zone",
    name: "Festival Futbolero Campos Revolución",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Campos Revolución",
    address: "Gustavo A. Madero, CDMX",
    lat: 19.4850,
    lng: -99.1180,
    entry: "Gratuita, sin alcohol",
    datesOpen: "11 jun – 19 jul 2026 (39 días, 104 partidos)",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede completa. Transmite todos los partidos del torneo.",
    active: true,
  },
  {
    id: "cdmx-garibaldi",
    type: "fan_zone",
    name: "Festival Futbolero Plaza Garibaldi",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Plaza Garibaldi",
    address: "Plaza Garibaldi, Cuauhtémoc, CDMX",
    lat: 19.4264,
    lng: -99.1394,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede de Cuauhtémoc. Transmite partidos de México y encuentros destacados. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-deportivo-galeana",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Hermanos Galeana",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Hermanos Galeana",
    address: "Gustavo A. Madero, CDMX",
    lat: 19.4950,
    lng: -99.1050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Transmite partidos de México y encuentros destacados.",
    active: true,
  },
  {
    id: "cdmx-iztapalapa",
    type: "fan_zone",
    name: "Festival Futbolero Iztapalapa",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Iztapalapa",
    address: "Iztapalapa, CDMX",
    lat: 19.3557,
    lng: -99.0554,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-coyoacan",
    type: "fan_zone",
    name: "Festival Futbolero Coyoacán",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Coyoacán",
    address: "Coyoacán, CDMX",
    lat: 19.3467,
    lng: -99.1617,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-tlalpan",
    type: "fan_zone",
    name: "Festival Futbolero Tlalpan",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Tlalpan",
    address: "Tlalpan, CDMX",
    lat: 19.2969,
    lng: -99.1661,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },
  {
    id: "cdmx-xochimilco",
    type: "fan_zone",
    name: "Festival Futbolero Xochimilco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Por confirmar — Xochimilco",
    address: "Xochimilco, CDMX",
    lat: 19.2571,
    lng: -99.1043,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Ubicación exacta por confirmar. Más info pronto.",
    active: true,
  },

  {
    id: "cdmx-bombilla",
    type: "fan_zone",
    name: "Festival Futbolero Parque La Bombilla",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque La Bombilla",
    address: "Álvaro Obregón, CDMX",
    lat: 19.3556,
    lng: -99.1800,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-tezozomoc",
    type: "fan_zone",
    name: "Festival Futbolero Parque Tezozómoc",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Tezozómoc",
    address: "Azcapotzalco, CDMX",
    lat: 19.4934,
    lng: -99.1756,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-parque-americas",
    type: "fan_zone",
    name: "Festival Futbolero Parque Las Américas",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque Las Américas",
    address: "Benito Juárez, CDMX",
    lat: 19.3964,
    lng: -99.1592,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-consolacion",
    type: "fan_zone",
    name: "Festival Futbolero Parque de la Consolación",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Parque de la Consolación",
    address: "Coyoacán, CDMX",
    lat: 19.3500,
    lng: -99.1650,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-san-mateo-atenco",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo San Mateo Atenco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo San Mateo Atenco",
    address: "Cuajimalpa, CDMX",
    lat: 19.3600,
    lng: -99.2900,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-leandro-valle",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Leandro Valle",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Leandro Valle",
    address: "Iztacalco, CDMX",
    lat: 19.3950,
    lng: -99.1050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-unidad-independencia",
    type: "fan_zone",
    name: "Festival Futbolero Unidad Independencia",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Unidad Independencia",
    address: "La Magdalena Contreras, CDMX",
    lat: 19.3150,
    lng: -99.2050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-tlahuac",
    type: "fan_zone",
    name: "Festival Futbolero Bosque de Tláhuac",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Bosque de Tláhuac",
    address: "Tláhuac, CDMX",
    lat: 19.2750,
    lng: -99.0050,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-vivanco",
    type: "fan_zone",
    name: "Festival Futbolero Deportivo Vivanco",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Deportivo Vivanco",
    address: "Tlalpan, CDMX",
    lat: 19.2900,
    lng: -99.1600,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },
  {
    id: "cdmx-eduardo-molina",
    type: "fan_zone",
    name: "Festival Futbolero Utopía Eduardo Molina",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Utopía Deportivo Eduardo Molina",
    address: "Venustiano Carranza, CDMX",
    lat: 19.4350,
    lng: -99.0850,
    entry: "Gratuita, sin alcohol",
    datesOpen: "Partidos de México y destacados",
    officialUrl: null,
    registrationUrl: null,
    notes: "Sede parcial. Sin venta de alcohol.",
    active: true,
  },

  // ─── GUADALAJARA / ZAPOPAN ────────────────────────────────────────────────────
  {
    id: "gdl-parque-rojo",
    type: "fan_zone",
    name: "Fan Zone Parque Rojo",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque Rojo",
    address: "Av. Vallarta / Juárez, Zapopan, Jalisco",
    lat: 20.6750,
    lng: -103.3551,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-parque-la-mujer",
    type: "fan_zone",
    name: "Fan Zone Parque La Mujer",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque La Mujer",
    address: "C. Santa Lucía, Zapopan, Jalisco",
    lat: 20.7300,
    lng: -103.4200,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-parque-ninas-ninos",
    type: "fan_zone",
    name: "Fan Zone Parque de Las Niñas y Los Niños",
    city: "Zapopan",
    country: "mexico",
    venue: "Parque de Las Niñas y Los Niños",
    address: "Prolongación Laureles, Zapopan, Jalisco",
    lat: 20.7250,
    lng: -103.3950,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 8,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
  {
    id: "gdl-plaza-las-americas",
    type: "fan_zone",
    name: "Fan Zone Plaza Las Américas",
    city: "Zapopan",
    country: "mexico",
    venue: "Plaza Las Américas",
    address: "Centro de Zapopan, Jalisco",
    lat: 20.7215,
    lng: -103.3925,
    entry: "Gratuita",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Capacidad 10,000 personas. Organizado por gobierno de Zapopan.",
    active: true,
  },
];

export async function seedCdmxGdlFanZones(): Promise<void> {
  for (const { id, ...data } of CDMX_GDL_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedCdmxGdlFanZones complete — ${CDMX_GDL_FAN_ZONES.length} documents written.`);
}

// ─── CANADÁ — 30 abril 2026 ───────────────────────────────────────────────────
// IDs nuevos con información corregida. Los viejos (fan-festival-toronto,
// fan-festival-vancouver) se desactivan vía patchFanZones().
const CANADA_FAN_ZONES: Array<{ id: string } & SeedRow> = [
  {
    id: "canada-toronto",
    type: "fan_festival",
    name: "FIFA Fan Festival Toronto",
    city: "Toronto",
    country: "canada",
    venue: "Fort York National Historic Site",
    address: "250 Fort York Blvd, Toronto, ON M5V 3K9",
    lat: 43.6359,
    lng: -79.4005,
    entry: "Gratuita",
    datesOpen: "12 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Bajo el lema The World in a City. Destaca la diversidad multicultural de Toronto.",
    active: true,
  },
  {
    id: "canada-vancouver",
    type: "fan_festival",
    name: "FIFA Fan Festival Vancouver",
    city: "Vancouver",
    country: "canada",
    venue: "Hastings Park — PNE Grounds",
    address: "2901 E Hastings St, Vancouver, BC V5K 0A1",
    lat: 49.2827,
    lng: -123.0348,
    entry: "Gratuita (asientos reservados en anfiteatro ticketados)",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: null,
    registrationUrl: null,
    notes: "Anfiteatro de 10,000 personas. Conciertos: Mötley Crüe y Kx5 (Deadmau5 + Kaskade) en julio.",
    active: true,
  },
];

export async function seedCanadaFanZones(): Promise<void> {
  for (const { id, ...data } of CANADA_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded fan zone: ${id}`);
  }
  console.log(`seedCanadaFanZones complete — ${CANADA_FAN_ZONES.length} documents written.`);
}

// ─── BAY AREA — nuevas fan zones ─────────────────────────────────────────────
const BAY_AREA_NEW_FAN_ZONES = [
  {
    id: "ba-spark-social-sf",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Spark Social SF",
    city: "San Francisco",
    country: "bay_area",
    venue: "Spark Social SF",
    address: "601 Mission Bay Blvd North, San Francisco, CA 94158",
    lat: 37.7695,
    lng: -122.3927,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jun – 19 jul 2026",
    officialUrl: "https://sparksocialsf.com/world-cup-watch-parties/",
    registrationUrl: null,
    notes: null,
    food: "Variedad de food vendors locales",
    alcohol: true,
    amenities: "Pantalla gigante al aire libre. Beer garden. Ambiente comunitario. Walk-in sin registro.",
    active: true,
    status: "active",
  },
  {
    id: "ba-treasure-island-gold-bar",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Celebration of Nations — Treasure Island",
    city: "San Francisco",
    country: "bay_area",
    venue: "Gold Bar Whiskey Distillery, Treasure Island",
    address: "1 Avenue of the Palms, Treasure Island, SF 94130",
    lat: 37.8232,
    lng: -122.3707,
    entry: "Gratis con RSVP — Requiere registro en TicketFairy",
    datesOpen: "19 jun – 27 jun 2026 (13 partidos confirmados)",
    officialUrl: "https://ticketfairy.com/tour/celebration-of-nations-waterfront-soccer-watch-parties",
    registrationUrl: "https://ticketfairy.com/tour/celebration-of-nations-waterfront-soccer-watch-parties",
    notes: "Vista al agua. Partidos: USA-Australia, Brazil-Haiti, Germany-Ivory Coast, Ecuador-Germany, Japan-Sweden, Turkey-USA, Norway-France, Uruguay-Spain, Panama-England, Colombia-Portugal, Jordan-Argentina.",
    food: "Opciones locales en el venue",
    alcohol: true,
    amenities: "Pantalla gigante con vista al Bay. Waterfront. Beer garden. 13 partidos confirmados jun 19-27.",
    active: true,
    status: "active",
  },
  {
    id: "ba-walnut-creek-lesher",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Walnut Creek — Lesher Center",
    city: "Walnut Creek",
    country: "bay_area",
    venue: "Hofmann Theater, Lesher Center for the Arts",
    address: "1601 Civic Drive, Walnut Creek, CA 94596",
    lat: 37.9101,
    lng: -122.0652,
    entry: "Gratis — Requiere reserva en LesherArtsCenter.org",
    datesOpen: "13 jun 2026 (12–7 PM)",
    officialUrl: "https://www.lesherartscenter.org",
    registrationUrl: "https://www.lesherartscenter.org",
    notes: "Capacidad limitada a 785 asientos. Partidos: Qatar vs Switzerland 12 PM, Brazil vs Morocco 3 PM.",
    food: null,
    alcohol: true,
    amenities: "Teatro climatizado con 785 asientos. Pantalla gigante. Reserva con anticipación — cupo limitado.",
    active: true,
    status: "active",
  },
  {
    id: "ba-richmond-red-oak",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Richmond — SS Red Oak Victory",
    city: "Richmond",
    country: "bay_area",
    venue: "SS Red Oak Victory Historic Ship",
    address: "1337 Canal Blvd Berth 5, Richmond, CA 94804",
    lat: 37.9137,
    lng: -122.3593,
    entry: "Gratis — Walk-in",
    datesOpen: "12 jun (5–9 PM) y 25 jun (7–9 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Richmond United Soccer Club.",
    food: null,
    alcohol: true,
    amenities: "Barco histórico con vista al agua. 2 fechas: 12 jun y 25 jun. Organizado por Richmond United SC.",
    active: true,
    status: "active",
  },
  {
    id: "ba-richmond-east-brother",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Richmond — East Brother Beer Co",
    city: "Richmond",
    country: "bay_area",
    venue: "East Brother Beer Company",
    address: "1001 Canal Blvd, Richmond, CA 94804",
    lat: 37.9125,
    lng: -122.3601,
    entry: "Gratis — Walk-in",
    datesOpen: "18 jun (5–9 PM) y 24 jun (5:30–9 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por Richmond United Soccer Club.",
    food: null,
    alcohol: true,
    amenities: "Brewery con ambiente futbolero. 2 fechas: 18 jun y 24 jun. Organizado por Richmond United SC.",
    active: true,
    status: "active",
  },
  {
    id: "ba-san-carlos-wheeler",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone San Carlos — Wheeler Plaza",
    city: "San Carlos",
    country: "bay_area",
    venue: "Wheeler Parking Plaza",
    address: "616 Laurel St, San Carlos, CA 94070",
    lat: 37.5070,
    lng: -122.2605,
    entry: "Gratis — Walk-in",
    datesOpen: "12 jun (6–8:30 PM) y Final 19 jul (12–7 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Organizado por City of San Carlos. Beer y wine disponibles para compra.",
    food: null,
    alcohol: true,
    amenities: "Plaza al aire libre. Beer y wine para compra. 2 fechas: USA vs Paraguay (12 jun) y Final (19 jul).",
    active: true,
    status: "active",
  },
  {
    id: "ba-redwood-city-courthouse",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Redwood City — Courthouse Square",
    city: "Redwood City",
    country: "bay_area",
    venue: "Courthouse Square",
    address: "2200 Broadway, Redwood City, CA 94063",
    lat: 37.4852,
    lng: -122.2364,
    entry: "Gratis — Walk-in",
    datesOpen: "18 jun (6–8:30 PM), 24 jun (6–7 PM), 25 jun (7–9:30 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "3 fechas confirmadas: USA-South Korea, Mexico-Czechia, USA-Türkiye.",
    food: null,
    alcohol: null,
    amenities: "Plaza al aire libre en downtown. 3 partidos confirmados: USA vs South Korea (18 jun), Mexico vs Czechia (24 jun), USA vs Türkiye (25 jun).",
    active: true,
    status: "active",
  },
  {
    id: "ba-san-mateo-central-park",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone San Mateo — Central Park",
    city: "San Mateo",
    country: "bay_area",
    venue: "Central Park",
    address: "50 East 5th Ave, San Mateo, CA 94401",
    lat: 37.5683,
    lng: -122.3228,
    entry: "Gratis — Walk-in",
    datesOpen: "25 jun 2026 (6:45 PM – partido 7 PM) + más fechas por confirmar",
    officialUrl: "https://www.cityofsanmateo.org/4960/Summer-2026-Soccer-Celebrations",
    registrationUrl: null,
    notes: "USA vs Türkiye confirmado 25 jun. Más partidos por anunciar.",
    food: null,
    alcohol: null,
    amenities: "Parque al aire libre. Pantalla gigante. USA vs Türkiye (25 jun). Más fechas por confirmar.",
    active: true,
    status: "active",
  },
  {
    id: "ba-santana-row",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "The Row Cup — Santana Row",
    city: "San Jose",
    country: "bay_area",
    venue: "Santana Row",
    address: "377 Santana Row, San Jose, CA 95128",
    lat: 37.3212,
    lng: -121.9490,
    entry: "Gratis — Walk-in (consumo pagado en restaurantes)",
    datesOpen: "11 jun – 19 jul 2026 (5 semanas)",
    officialUrl: "https://santanarow.com/event/the-row-cup/",
    registrationUrl: null,
    notes: "Watch parties en 15+ restaurantes. FIFA Pop-Up Shop 10 jun – 19 jul.",
    food: "15+ restaurantes: Augustine, Left Bank, Dumpling Time, EMC Seafood, El Jardin, Momosan y más",
    alcohol: true,
    amenities: "FIFA Pop-Up Shop. Live DJs. Happy hours en Vintage Wine Bar. 15+ restaurantes participantes. 5 semanas completas.",
    active: true,
    status: "active",
  },
  {
    id: "ba-morgan-hill",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Morgan Hill — Soccer Kickoff Festival",
    city: "Morgan Hill",
    country: "bay_area",
    venue: "Morgan Hill Outdoor Sports Center",
    address: "16500 Condit Rd, Morgan Hill, CA 95037",
    lat: 37.1305,
    lng: -121.6543,
    entry: "Gratis — Walk-in",
    datesOpen: "13 jun 2026 (9 AM – 5 PM)",
    officialUrl: "https://visitmorganhill.org/event-calendar-detail/soccerfest26",
    registrationUrl: null,
    notes: "Partidos: Qatar vs Switzerland (12 PM) y Brazil vs Morocco (3 PM).",
    food: null,
    alcohol: null,
    amenities: "Outdoor Sports Center. Partidos Qatar-Switzerland y Brazil-Morocco. Organizado por City of Morgan Hill y OV Toros.",
    active: true,
    status: "active",
  },
  {
    id: "ba-milpitas",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Milpitas — Taste of Milpitas",
    city: "Milpitas",
    country: "bay_area",
    venue: "Milpitas Community Center",
    address: "457 E Calaveras Blvd, Milpitas, CA 95035",
    lat: 37.4323,
    lng: -121.8996,
    entry: "Gratis — Walk-in",
    datesOpen: "20 jun 2026 (3–9 PM)",
    officialUrl: "https://mvblfeast.com/taste-of-milpitas/",
    registrationUrl: null,
    notes: "Evento Taste of Milpitas con watch party incluido.",
    food: "Feria gastronómica Taste of Milpitas",
    alcohol: null,
    amenities: "Feria gastronómica + watch party. 20 jun 3-9 PM.",
    active: true,
    status: "active",
  },
  {
    id: "ba-santa-cruz-boardwalk",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Santa Cruz Beach Boardwalk",
    city: "Santa Cruz",
    country: "bay_area",
    venue: "Santa Cruz Beach Boardwalk",
    address: "400 Beach St, Santa Cruz, CA 95060",
    lat: 36.9641,
    lng: -122.0177,
    entry: "Gratis — Walk-in",
    datesOpen: "25 jun 2026 (7–9:30 PM) + más fechas",
    officialUrl: "https://beachboardwalk.com/world-soccer-celebration/",
    registrationUrl: null,
    notes: "USA vs Türkiye confirmado 25 jun. Pantalla LED gigante en la arena.",
    food: "Opciones del Boardwalk",
    alcohol: true,
    amenities: "Pantalla LED gigante. Beer garden frente al Colonnade. Vista al océano. USA vs Türkiye (25 jun).",
    active: true,
    status: "active",
  },
  {
    id: "ba-downtown-oakland",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Downtown Oakland",
    city: "Oakland",
    country: "bay_area",
    venue: "Oakland Marriott City Center",
    address: "1001 Broadway, Oakland, CA 94607",
    lat: 37.8044,
    lng: -122.2711,
    entry: "Gratis — Walk-in",
    datesOpen: "19 jun 2026 (12–3 PM)",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: null,
    food: null,
    alcohol: null,
    amenities: "Downtown Oakland. 19 jun 12-3 PM.",
    active: true,
    status: "active",
  },
  {
    id: "ba-jackson-playground-sf",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Jackson Playground SF",
    city: "San Francisco",
    country: "bay_area",
    venue: "Jackson Playground",
    address: "1645 17th St, San Francisco, CA 94107",
    lat: 37.7652,
    lng: -122.3969,
    entry: "Gratis — Walk-in",
    datesOpen: "11 jul 2026 (2–7 PM) — Cuartos de Final",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Cuartos de Final. Organizado por el vecindario.",
    food: null,
    alcohol: null,
    amenities: "Parque al aire libre. Cuartos de Final (11 jul). Organizado por la comunidad.",
    active: true,
    status: "active",
  },
  // ─── PRÓXIMAMENTE — anunciados sin fecha confirmada ──────────────────────
  {
    id: "ba-sausalito",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Sausalito",
    city: "Sausalito",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Sausalito, CA",
    lat: 37.8590,
    lng: -122.4852,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-napa-valley",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Napa Valley",
    city: "Napa",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Napa, CA",
    lat: 38.2975,
    lng: -122.2869,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-santa-rosa",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Santa Rosa",
    city: "Santa Rosa",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Santa Rosa, CA",
    lat: 38.4404,
    lng: -122.7141,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-half-moon-bay",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Half Moon Bay",
    city: "Half Moon Bay",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Half Moon Bay, CA",
    lat: 37.4636,
    lng: -122.4286,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-mountain-view",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Mountain View",
    city: "Mountain View",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Mountain View, CA",
    lat: 37.3861,
    lng: -122.0839,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-burlingame",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Burlingame",
    city: "Burlingame",
    country: "bay_area",
    venue: "Por confirmar",
    address: "Burlingame, CA",
    lat: 37.5842,
    lng: -122.3660,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-sunnyvale",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Cityline Sunnyvale",
    city: "Sunnyvale",
    country: "bay_area",
    venue: "Cityline Sunnyvale",
    address: "Sunnyvale, CA",
    lat: 37.3688,
    lng: -122.0363,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-milpitas-civic",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Milpitas Civic Center Plaza",
    city: "Milpitas",
    country: "bay_area",
    venue: "Civic Center Plaza",
    address: "456 E Calaveras Blvd, Milpitas, CA 95035",
    lat: 37.4320,
    lng: -121.8990,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
  {
    id: "ba-santa-cruz-mah",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Santa Cruz — Museum of Art & History",
    city: "Santa Cruz",
    country: "bay_area",
    venue: "Santa Cruz Museum of Art & History",
    address: "705 Front St, Santa Cruz, CA 95060",
    lat: 36.9741,
    lng: -122.0308,
    entry: "Por confirmar",
    datesOpen: "Por confirmar",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Anunciado por el Bay Area Host Committee. Fechas y venue por confirmar.",
    food: null,
    alcohol: null,
    amenities: null,
    active: true,
    status: "coming_soon",
  },
];

export async function seedBayAreaNewFanZones(): Promise<void> {
  for (const { id, ...data } of BAY_AREA_NEW_FAN_ZONES) {
    await setDoc(doc(db, "wc2026_fanzones", id), {
      ...data,
      updatedAt: serverTimestamp(),
    });
    console.log(`Seeded bay area fan zone: ${id}`);
  }
  console.log(`seedBayAreaNewFanZones complete — ${BAY_AREA_NEW_FAN_ZONES.length} documents written.`);
}

// ─── PARCHES — correcciones sobre documentos ya existentes ───────────────────
// Usa setDoc con merge:true para no sobreescribir campos no mencionados.
type PatchRow = { id: string } & Record<string, unknown>;

const PATCHES: PatchRow[] = [
  // Rockefeller: era fan_zone genérico → es fan_festival FIFA x Telemundo
  {
    id: "fan-village-rockefeller-ny",
    type: "fan_festival",
    name: "Fan Village Rockefeller Center — FIFA x Telemundo",
    datesOpen: "6 jul – 19 jul 2026",
    entry: "Ticketada ($12.50)",
    notes: "Asociación FIFA y Telemundo. La pista de patinaje se convierte en campo de fútbol con pantallas gigantes.",
  },
  // Toronto viejo → desactivar (reemplazado por canada-toronto)
  {
    id: "fan-festival-toronto",
    active: false,
  },
  // Vancouver viejo → desactivar (reemplazado por canada-vancouver)
  {
    id: "fan-festival-vancouver",
    active: false,
  },
  // Guadalajara → nota actualizada con Zapopan confirmado
  {
    id: "fan-festival-guadalajara",
    notes: "Plaza de la Liberación. 39 días, 104 partidos. Acceso libre y gratuito. Fan Zones adicionales en Zapopan confirmados.",
  },
  // Jersey City → cancelado oficialmente en febrero 2026
  {
    id: "nj-jersey-city",
    active: false,
  },
  // Monumento a la Revolución → reemplazado por cdmx-garibaldi (Plaza Garibaldi)
  {
    id: "cdmx-monumento-revolucion",
    active: false,
  },
  // ─── USA — COMPLETO ───────────────────────────────────────────────────────────

  // Fan Festivals oficiales
  {
    id: "fan-festival-philadelphia",
    food: "~80 food trucks del área de Philadelphia",
    alcohol: true,
    amenities: "Múltiples pantallas gigantes en 1 millón de sq ft. DJ y música en vivo. Activaciones FIFA, giveaways, photo ops, juegos interactivos. 39 días completos, el único Fan Festival USA con corrida completa. Capacidad 15,000-20,000/día. Horario 11am-medianoche. Requiere registro en phillyfwc26.com.",
  },
  {
    id: "fan-festival-dallas",
    food: "Food courts locales en Lots 9 y 10 + Pavilion",
    alcohol: true,
    amenities: "Pantallas gigantes en 1 millón de sq ft. Conciertos en vivo en Dos Equis Pavilion (7,000 asientos cubiertos). Mini-pitches, skills contests, zonas de patrocinadores. VIP: GA+ con Starplex Lounge exclusivo. Capacidad 35,000 simultáneos. Producido por C3 Presents (Lollapalooza).",
  },
  {
    id: "fan-festival-houston",
    food: "Opciones locales de Houston: vietnamita, BBQ, italiano",
    alcohol: true,
    amenities: "9 pantallas grandes. Esphera: domo de proyección 360° del Space Center Houston. Torneo 7v7 U11-U18. Misting zones, agua, sombra y médicos on-site. Green Corridor al estadio por METRORail. Gratis, sin registro.",
  },
  {
    id: "fan-festival-kansas-city",
    food: "Restaurantes locales y regionales de Kansas City",
    alcohol: true,
    amenities: "Pantalla principal 4,200 sq ft. Conciertos: The Chainsmokers, Flo Rida, Gabby Barrett, The All-American Rejects, Tech N9ne. KC Heart Gateway entrada 65 ft. Pet-friendly: Dog Days con Purina domingos 14 jun, 21 jun y 5 jul. VIP: Premium Garden Pass $55 / Legacy Lounge $225 all-inclusive. Registro vía FIFA app.",
  },
  {
    id: "fan-festival-miami",
    food: "Gastronomía local de Miami, diversidad culinaria",
    alcohol: true,
    amenities: "Pantallas LED gigantes. Anfiteatro 10,000 personas. Conciertos y DJs internacionales. Instalación interactiva Faces of Fan Festival. Vista a Biscayne Bay. Misting zones, sombra, hidratación. Gratis, 30,000 personas/día.",
  },
  {
    id: "fan-festival-atlanta",
    food: "Food stalls locales y opciones internacionales en Georgia Street",
    alcohol: true,
    amenities: "Pantalla 40 ft en Main Stage. 4 zonas: Main Stage (conciertos), The Playground (activaciones), The Pitch (podcasts AR/VR), Georgia Street (artistas y comida). VIP desde $30 hasta $10,000. Conmemora 30 años Juegos Olímpicos 1996. Registro previo requerido.",
  },
  {
    id: "fan-festival-boston",
    food: "Gastronomía local de Boston curada",
    alcohol: true,
    amenities: "Jumbotron grande. Cultural Showcase con artistas y músicos locales. Apariciones de leyendas FIFA y mascotas oficiales 2026. Área de juegos con balones y habilidades. Solo Group Stage: 12-27 jun (16 días). Capacidad 20,000-25,000. Requiere registro previo.",
  },
  {
    id: "fan-festival-los-angeles",
    food: "Gastronomía inspirada en países participantes. Evento cashless",
    alcohol: true,
    amenities: "Pantallas grandes. DJ y entretenimiento cultural. Road to World Cup Community Day by Amgen. Clinics Grow the Game. VIP: Club Seats $30, Hospitality Tower Lounge $30. Sala sensorial disponible. Solo Opening Weekend: 11-14 jun. Entrada GA $10, niños -12 gratis.",
  },

  // Bay Area
  {
    id: "fan-zone-thrive-city-sf",
    food: "Vendors locales en plaza al aire libre",
    alcohol: true,
    amenities: "Pantalla gigante al aire libre. Activaciones de Kaiser Permanente, Genentech y PG&E. Solo 2 fechas: 12 jun (USA vs Paraguay) y 18 jun (México vs Corea del Sur). Gratis con RSVP.",
  },
  {
    id: "fan-zone-san-pedro-square-sj",
    food: "Menús temáticos por país participante",
    alcohol: true,
    amenities: "2 pantallas gigantes. DJ pre-partido y halftime. Face painting, juegos, giveaways, Soccer Village familiar. Meet & greets con leyendas. VIP Zone para Season Ticket Holders. 39 días completos. Gratis con RSVP.",
  },
  {
    id: "sf-china-basin",
    food: "Restaurantes Mission Rock adyacentes",
    alcohol: true,
    amenities: "Pantallas grandes. Great Lawn, vista a McCovey Cove, Bay Trail. Pet-friendly. Solo match days seleccionados; especiales en semis (14 jul) y Final (19 jul). Gratis.",
  },
  {
    id: "sf-pier39",
    food: "Restaurantes y food stalls del Pier",
    alcohol: true,
    amenities: "Beer garden. Pantallas para partidos selectos. Sea lions, atracciones familiares. Solo USA matches, Round of 16, Cuartos, Semis y Final. Gratis.",
  },
  {
    id: "oak-raimondi-park",
    food: "Food vendors en Prescott Marketplace adyacente",
    alcohol: true,
    amenities: "Pantallas grandes. Organizado por Oakland Roots SC y Oakland Ballers. Solo 1 fecha confirmada: 12 jun 5-9pm (USA vs Paraguay). RSVP vía TicketLeap. Gratis.",
  },

  // Nueva York
  {
    id: "fan-zone-queens-ny",
    food: "Vendors locales representando las 190 nacionalidades de Queens",
    alcohol: true,
    amenities: "Louis Armstrong Stadium como venue principal, capacidad 10,000. DJ y entretenimiento familiar. Juegos interactivos, cultural showcases, merch oficial. VIP disponible. Tren 7 directo desde Times Square. 11-27 jun. Requiere ticket anticipado en Live Nation.",
  },
  {
    id: "fan-village-rockefeller-ny",
    food: "Desde casual bites hasta restaurantes de destino en Rockefeller Center",
    alcohol: true,
    amenities: "La pista de Rockefeller convertida en campo con pantallas gigantes. Champions Garden homenaje a 8 naciones campeonas. Exposición inmersiva Legacies of Champions por Hyundai gratis con timed-entry. LEGO build station. 10% off FIFA Store. Extended hours Finals Week. 4-19 jul. Gratis.",
  },
  {
    id: "fan-hub-harrison-nj",
    food: "Vendors locales del estadio",
    alcohol: true,
    amenities: "Live match viewings. Cultural programming y performances musicales. PATH train desde World Trade Center. Fechas selectas durante el torneo. NOTA: cuesta $10/día, niños -12 gratis con ticket.",
  },
  {
    id: "ny-brooklyn",
    food: "Vendors representando la gastronomía de Brooklyn",
    alcohol: true,
    amenities: "Pantallas con vista al skyline de Manhattan desde el East River. Daily programming, música, waterfront. La corrida más larga de los 5 boroughs: 13 jun - 19 jul (37 días). Gratis con registro.",
  },
  {
    id: "ny-bronx",
    food: null,
    alcohol: true,
    amenities: "Matchday viewings en Bronx Terminal Market. Solo 2 días: 13-14 jun. Gratis con registro.",
  },
  {
    id: "ny-staten-island",
    food: null,
    alcohol: true,
    amenities: "Evening matches con vista al skyline. Acceso vía Staten Island Ferry. 29 jun - 2 jul. Gratis con registro.",
  },
  {
    id: "nj-jersey-city",
    food: null,
    alcohol: false,
    amenities: "CANCELADO — Liberty State Park fue cancelado oficialmente en febrero 2026.",
    active: false,
  },

  // Los Ángeles
  {
    id: "la-union-station",
    food: "Food trucks y vendors locales",
    alcohol: true,
    amenities: "Acceso directo Metro A/B/D/J. Plaza de Cultura y Artes adyacente. 25-28 jun. Gratis.",
  },
  {
    id: "la-hansen-dam",
    food: "Gastronomía global y food vendors",
    alcohol: true,
    amenities: "DJ performances. Beer garden. Classic cars, muralistas, juegos con premios. 2-5 jul. Gratis.",
  },
  {
    id: "la-magic-johnson-park",
    food: "Food trucks y community marketplace",
    alcohol: true,
    amenities: "Family activities, música. Earvin Magic Johnson Park, Willowbrook. 4-5 jul. Gratis.",
  },
  {
    id: "la-whittier-narrows",
    food: "Eats locales del San Gabriel Valley",
    alcohol: true,
    amenities: "Actividades culturales. 9-11 jul. Gratis.",
  },
  {
    id: "la-fairplex",
    food: "Food vendors globales",
    alcohol: true,
    amenities: "Beer gardens. Música en vivo, DJs, performances culturales. Programación familiar. 14-15 jul y 18-19 jul. Gratis.",
  },
  {
    id: "la-west-harbor",
    food: "Vendors en zona waterfront",
    alcohol: true,
    amenities: "Fan zone frente al mar, San Pedro. 14-15 jul y 18-19 jul. Gratis.",
  },
  {
    id: "la-burbank",
    food: "Vendors locales de Burbank",
    alcohol: true,
    amenities: "Día de la Final. VIP experience $300+ con viewing lounge y concierto. 18-19 jul.",
  },

  // Washington State
  {
    id: "wa-bellingham",
    food: "Food trucks y opciones de brewery",
    alcohol: true,
    amenities: "Kulshan Brewing Trackside + The Den + Wild Buffalo. Outdoor block party en 1300 block Commercial St. Gratis.",
  },
  {
    id: "wa-bremerton",
    food: "Food trucks",
    alcohol: true,
    amenities: "Giant LED screen. 8 zonas únicas. Beer gardens. Eventos especiales Juneteenth y 250th anniversary USA. Quincy Square. Gratis.",
  },
  {
    id: "wa-tacoma",
    food: "Food trucks",
    alcohol: true,
    amenities: "Cultural exchange tribal en Puyallup Tribal Headquarters. Gratis.",
  },
  {
    id: "wa-spokane",
    food: "Food trucks",
    alcohol: true,
    amenities: "Gesa Pavilion at Riverfront Park. Gratis.",
  },
  {
    id: "wa-everett",
    food: "Food trucks",
    alcohol: true,
    amenities: "Boxcar Park, Port of Everett. Waterfront fan zone. Gratis.",
  },
  {
    id: "wa-olympia",
    food: "Food trucks",
    alcohol: true,
    amenities: "Waterfront fan zone. Gratis.",
  },
  {
    id: "wa-yakima",
    food: "Food trucks",
    alcohol: true,
    amenities: "Family fun y cultural exchange. Gratis.",
  },
  {
    id: "wa-tri-cities",
    food: "Food trucks",
    alcohol: true,
    amenities: "Pasco Sporting Complex. Gratis.",
  },
  // ─── MÉXICO ───────────────────────────────────────────────────────────────────
  {
    id: "fan-festival-cdmx",
    food: "Gastronomía mexicana desde lo popular hasta lo gourmet, complementada con sabores internacionales",
    alcohol: false,
    amenities: "Pantalla LED de 510 m² — la más grande del torneo a nivel mundial. Conciertos en vivo y DJs. Experiencia inmersiva El Juego Eterno. Canchas de futbol abiertas. Tienda oficial FIFA. Ceremonia inaugural 11 jun con Alejandro Fernández, Belinda, J Balvin, Maná, Lila Downs, Los Ángeles Azules y más. 39 días completos, 104 partidos. Capacidad 55,000-60,000/día. Gratis SIN registro previo. Zona VIP estilo F1 con bar completo (única excepción al policy sin alcohol).",
  },
  {
    id: "fan-festival-monterrey",
    food: "Gastronomía local de Monterrey, zonas de convivencia",
    alcohol: true,
    amenities: "Pantallas gigantes. 20 artistas en vivo: Chayanne (13 jun), Enrique Iglesias, Imagine Dragons, Grupo Firme, Leyenda (11 jun), Parranda (12 jun), Caballo Dorado (14 jun), más rock, regional mexicano, cumbia, ska y electrónica. VIP pagado con bar y mejor vista al escenario (Ticketmaster). Acceso general gratis sin registro, sujeto a cupo por orden de llegada. 39 días.",
  },
  {
    id: "fan-festival-guadalajara",
    food: "Corredor gastronómico en Plaza de Armas: birria, tortas ahogadas, jericallas y sabores tradicionales de Jalisco",
    alcohol: true,
    amenities: "5 pantallas gigantes para los 104 partidos. Concepto La Fiesta más Mexicana. Talleres artísticos en Teatro Degollado. Exhibiciones deportivas familiares. Tren Ligero Línea 3 directo. 4,000 voluntarios. Capacidad 40,000 simultáneos. Gratis sin registro. 39 días.",
  },
  {
    id: "cdmx-chapultepec-cricri",
    food: "Feria gastronómica de pueblos originarios y productos de chinampas",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol abiertas. Concurso de penales y dominadas. Exposiciones escultóricas: ajolotes intervenidos y alebrijes. Programación de cine, animación y baile familiar. Zona infantil. Transmite los 104 partidos, 39 días completos. Gratis sin alcohol.",
  },
  {
    id: "cdmx-utopia-meyehualco",
    food: "Feria gastronómica de pueblos originarios",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol abiertas. Sonideros, batucadas, comparsas. Zona infantil. Transmite los 104 partidos, 39 días completos. Gratis sin alcohol.",
  },
  {
    id: "cdmx-campos-revolucion",
    food: "Feria gastronómica local",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol abiertas. Música popular y sonideros. Zona infantil. Transmite los 104 partidos, 39 días completos. Gratis sin alcohol.",
  },
  {
    id: "cdmx-garibaldi",
    food: "Gastronomía local de Cuauhtémoc",
    alcohol: false,
    amenities: "Pantalla gigante. Plaza Garibaldi. Música popular, mariachis. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-deportivo-galeana",
    food: "Feria gastronómica local",
    alcohol: false,
    amenities: "Pantalla gigante. Canchas de futbol. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-iztapalapa",
    food: "Feria gastronómica de Iztapalapa",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Ubicación exacta por confirmar. Gratis sin alcohol.",
  },
  {
    id: "cdmx-coyoacan",
    food: "Gastronomía local de Coyoacán",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Ubicación exacta por confirmar. Gratis sin alcohol.",
  },
  {
    id: "cdmx-tlalpan",
    food: "Gastronomía local de Tlalpan",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Ubicación exacta por confirmar. Gratis sin alcohol.",
  },
  {
    id: "cdmx-xochimilco",
    food: "Gastronomía de Xochimilco, productos de chinampas",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-bombilla",
    food: "Feria gastronómica local de Álvaro Obregón",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-tezozomoc",
    food: "Feria gastronómica local de Azcapotzalco",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-parque-americas",
    food: "Gastronomía local de Benito Juárez",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-consolacion",
    food: "Gastronomía local de Coyoacán",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-san-mateo-atenco",
    food: "Gastronomía local de Cuajimalpa",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-leandro-valle",
    food: "Gastronomía local de Iztacalco",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-unidad-independencia",
    food: "Gastronomía local de La Magdalena Contreras",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-tlahuac",
    food: "Gastronomía local de Tláhuac",
    alcohol: false,
    amenities: "Pantalla gigante. Bosque de Tláhuac. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-vivanco",
    food: "Gastronomía local de Tlalpan",
    alcohol: false,
    amenities: "Pantalla gigante. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "cdmx-eduardo-molina",
    food: "Gastronomía local de Venustiano Carranza",
    alcohol: false,
    amenities: "Pantalla gigante. Utopía Deportivo Eduardo Molina. Zona infantil. Partidos de México y encuentros destacados. Gratis sin alcohol.",
  },
  {
    id: "gdl-parque-rojo",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Actividades familiares. Frente a Basílica de Zapopan. Capacidad ~8,000. Gratis. 39 días.",
  },
  {
    id: "gdl-parque-la-mujer",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Programación cultural. Capacidad ~8,000. Gratis. 39 días.",
  },
  {
    id: "gdl-parque-ninas-ninos",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Actividades familiares. Capacidad ~8,000. Gratis. 39 días.",
  },
  {
    id: "gdl-plaza-las-americas",
    food: "Gastronomía local de Zapopan",
    alcohol: true,
    amenities: "Pantalla gigante. Estacionamiento subterráneo disponible. Capacidad ~10,000. Gratis. 39 días.",
  },
  // ─── CANADÁ ───────────────────────────────────────────────────────────────────
  {
    id: "canada-toronto",
    food: "Street Eats con 30+ vendors sirviendo sabores globales y pastries canadienses",
    alcohol: true,
    amenities: "Múltiples pantallas en Fort York y The Bentway. Conciertos: Alessia Cara, Bedouin Soundclash, Big Wreck, Walk off the Earth, Kardinal Offishall. Ontario Pitch (mini-golf temático). LEGO build station. Tkaronto Market (espacio de vendors indígenas). FIFA Store. VIP: Casamigos Clubhouse (lounge doble piso climatizado), Garden Pavilion y Pitchside Terrace — desde $100 hasta $300. 22 event days. GA gratis pero requiere reservación Ticketmaster (se agota rápido). Sin estacionamiento general, solo transporte público.",
  },
  {
    id: "canada-vancouver",
    food: "Gastronomía elevada con opciones locales de Vancouver",
    alcohol: true,
    amenities: "Anfiteatro PNE con capacidad 10,000. 60+ conciertos gratuitos en Park Stage. Conciertos pagados en anfiteatro: Mötley Crüe (12 jul), KX5 — Kaskade + Deadmau5 (17 jul). Conciertos gratis destacados: Chromeo (18 jun), Metric + Ozomatli (26 jun), Simple Plan (2 jul), Ziggy Marley (3 jul), Thievery Corporation (5 jul), Arkells (7 jul), Kaytranada en la Final (19 jul). Pantallas en todo el site para los 46 partidos. Activaciones FIFA. 28 días continuos. GA gratis, asientos anfiteatro desde $44 lawn / $115 reserved. Expo Line a 29th Avenue Station.",
  },
  // ─── PRECIOS CORREGIDOS ───
  { id: "fan-festival-los-angeles", entry: "Desde $10 GA / $30 VIP — Requiere ticket en Ticketmaster" },
  { id: "fan-hub-harrison-nj", entry: "Desde $10/día — Requiere ticket en SI Tickets" },
  { id: "la-burbank", entry: "VIP desde $300 — Requiere ticket (Final 18-19 jul)" },
  { id: "fan-festival-kansas-city", entry: "Gratis GA con registro · VIP $55 Garden Pass / $225 Legacy Lounge" },
  { id: "fan-festival-atlanta", entry: "Gratis GA con registro · VIP desde $45 hasta $325" },
  { id: "canada-toronto", entry: "Gratis GA con registro en Ticketmaster (agotado) · VIP desde $122 CAD" },
  { id: "canada-vancouver", entry: "Gratis · Conciertos premium desde $44 CAD en anfiteatro" },
  { id: "fan-festival-monterrey", entry: "Gratis GA walk-in · VIP conciertos desde $850 MXN en Ticketmaster" },

  // ─── REGISTRATION URLS ───
  // USA — Fan Festivals oficiales
  { id: "fan-festival-philadelphia", officialUrl: "https://phillyfwc26.com/fifa-fan-fest", registrationUrl: "https://phillyfwc26.com/fifa-fan-fest" },
  { id: "fan-festival-dallas", officialUrl: "https://www.dallasfwc26.com/our-venues/fan-festival/", registrationUrl: "https://www.dallasfwc26.com/our-venues/fan-festival/" },
  { id: "fan-festival-houston", officialUrl: "https://www.fwc26houston.com/fifafanfestivalhou", registrationUrl: "https://www.fwc26houston.com/fifafanfestivalhou" },
  { id: "fan-festival-kansas-city", officialUrl: "https://kansascityfwc26.com/fifa-fan-festival/", registrationUrl: "https://kansascityfwc26.com/fifa-fan-festival/" },
  { id: "fan-festival-miami", officialUrl: "https://miamifwc26.com/fan-festival/", registrationUrl: "https://miamifwc26.com/fan-festival/" },
  { id: "fan-festival-atlanta", officialUrl: "https://atlantafwc26.com/fan-fest/tickets/", registrationUrl: "https://atlantafwc26.com/fan-fest/tickets/" },
  { id: "fan-festival-boston", officialUrl: "https://bostonfwc26.com/fifa-fan-festival/", registrationUrl: "https://bostonfwc26.com/fifa-fan-festival/" },
  { id: "fan-festival-los-angeles", officialUrl: "https://losangelesfwc26.com/fifa-fan-festival-los-angeles/", registrationUrl: "https://www.ticketmaster.com/fifa-fan-festival-los-angeles-tickets/artist/4256617" },

  // USA — Bay Area
  { id: "fan-zone-thrive-city-sf", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "fan-zone-san-pedro-square-sj", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "sf-china-basin", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "sf-pier39", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "oak-raimondi-park", officialUrl: "https://www.sfbayareafwc26.com/bay-area-events", registrationUrl: "https://events.ticketleap.com/tickets/oaklandroots/raimondi-world-cup-watch-party-usa-vs-paraguay" },

  // USA — Nueva York
  { id: "fan-zone-queens-ny", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },
  { id: "fan-village-rockefeller-ny", officialUrl: "https://www.rockefellercenter.com/events/world-cup-2026", registrationUrl: "https://www.rockefellercenter.com/events/world-cup-2026" },
  { id: "fan-hub-harrison-nj", officialUrl: "https://www.sportsillustratedstadium.com/fan-hub", registrationUrl: "https://www.sportsillustratedstadium.com/fan-hub" },
  { id: "ny-brooklyn", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },
  { id: "ny-bronx", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },
  { id: "ny-staten-island", officialUrl: "https://nynjfwc26.com/fan-zones/", registrationUrl: "https://nynjfwc26.com/fan-zones/" },

  // USA — Los Ángeles Fan Zones
  { id: "la-union-station", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://fan-zone-26-at-union-station.eventbrite.com/" },
  { id: "la-hansen-dam", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.fanzonehdl.com/e/hansen-dam-lake-fan-zone" },
  { id: "la-magic-johnson-park", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.eventbrite.com/e/los-angeles-world-cup-26-fan-zone-at-la-countys-magic-johnson-park-tickets-1985958563524" },
  { id: "la-whittier-narrows", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.eventbrite.com/e/los-angeles-world-cup-26-fan-zone-at-los-angeles-county-whittier-narrows-tickets-1985936648977" },
  { id: "la-fairplex", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://www.discoverlosangeles.com/event/2026/07/14/los-angeles-world-cup-26-fan-zone-at-fairplex" },
  { id: "la-west-harbor", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://tickets.westharborla.com/" },
  { id: "la-burbank", officialUrl: "https://losangelesfwc26.com/los-angeles-world-cup-26-fan-zones/", registrationUrl: "https://tickets.cbfproductions.com/e/los-angeles-world-cup-26-fan-zone-downtown-burbank" },

  // Canadá
  { id: "canada-toronto", officialUrl: "https://torontofwc26.ca/FIFAFanFestival", registrationUrl: "https://www.ticketmaster.ca/fifa-fan-festival-toronto-tickets/artist/4331999" },
  { id: "canada-vancouver", officialUrl: "https://www.vancouverfwc26.ca/fifa-fan-festival", registrationUrl: "https://www.vancouverfwc26.ca/fifa-fan-festival" },

  // ─── BAY AREA COUNTRY UPDATE ───
  { id: "fan-zone-thrive-city-sf", country: "bay_area" },
  { id: "fan-zone-san-pedro-square-sj", country: "bay_area" },
  { id: "sf-china-basin", country: "bay_area" },
  { id: "sf-pier39", country: "bay_area" },
  { id: "oak-raimondi-park", country: "bay_area" },
  // México
  { id: "fan-festival-cdmx", officialUrl: "https://mexicocityfwc26.com.mx/fifa-fan-festival-cdmx", registrationUrl: null },
  { id: "fan-festival-guadalajara", officialUrl: "https://gdl2026.com", registrationUrl: null },
  { id: "fan-festival-monterrey", officialUrl: "https://www.fwc26monterrey.com", registrationUrl: "https://www.ticketmaster.com.mx/fifa-fan-festival-monterrey-boletos/artist/4444364" },

  // ─── JUNIO 2026 — Correcciones datesOpen verificadas vs sfbayareafwc26.com ───
  { id: "sf-pier39", datesOpen: "12 jun – 19 jul 2026 (fechas selectas: USA Jun 12, 19, 25; Octavos Jul 5-7; Cuartos Jul 9-11; Semis Jul 14-15; Final Jul 19)" },
  { id: "sf-china-basin", datesOpen: "13 jun – 19 jul 2026 (fechas selectas de partido)" },
  { id: "ba-redwood-city-courthouse", datesOpen: "23 jun – 19 jul 2026 (watch parties al aire libre con días temáticos)" },
  { id: "oak-raimondi-park", datesOpen: "12 jun 2026 (5–9 PM, USA vs Paraguay)" },
  { id: "ba-alameda-county-fair", datesOpen: "19 jun – 11 jul 2026 (solo miércoles a domingo, 12pm-11pm, gratis con entrada al Fair)" },
  { id: "fan-zone-san-pedro-square-sj", datesOpen: "11 jun – 19 jul 2026 (los 104 partidos, transmisión continua, gratis con RSVP)" },
  { id: "ba-napa-ruins", datesOpen: "11 jun – 19 jul 2026 (partidos seleccionados: Jun 11, 12, 19, 25, 26, 27; Semis Jul 14-15; Final Jul 19)" },
];

export async function patchFanZones(): Promise<void> {
  for (const { id, ...data } of PATCHES) {
    await setDoc(
      doc(db, "wc2026_fanzones", id),
      { ...data, updatedAt: serverTimestamp() },
      { merge: true }
    );
    console.log(`Patched fan zone: ${id}`);
  }
  console.log(`patchFanZones complete — ${PATCHES.length} documents patched.`);
}

// ─── USA EXPANSION — Mayo 2026 ────────────────────────────────────────────────
// 13 nuevos Fan Zones: Seattle, LA extra, Pennsylvania, Massachusetts, Washington
const USA_EXPANSION_2026: Array<{ id: string } & SeedRow> = [
  {
    id: "fan-festival-seattle",
    tournament: "world_cup_2026",
    type: "fan_festival",
    name: "FIFA Fan Festival Seattle",
    city: "Seattle",
    country: "usa",
    venue: "Lumen Field Area",
    address: "800 Occidental Ave S, Seattle, WA 98134",
    lat: 47.5952,
    lng: -122.3316,
    entry: "Gratis",
    datesOpen: "Por confirmar — detalles pendientes",
    officialUrl: "https://seattlefwc26.org",
    registrationUrl: null,
    notes: "Seattle implementó modelo híbrido con Unity Loop y Fan Zones regionales en todo Washington State.",
    food: "Por confirmar",
    alcohol: true,
    amenities: "Pantallas gigantes, actividades culturales",
    active: true,
    status: "active",
  },
  {
    id: "la-farmers-market",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Original Farmers Market",
    city: "Los Ángeles",
    country: "usa",
    venue: "The Original Farmers Market",
    address: "6333 W 3rd St, Los Angeles, CA 90036",
    lat: 34.0736,
    lng: -118.3626,
    entry: "Desde $5/día — paquete 4 días $17",
    datesOpen: "18–21 jun 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: "https://losangelesfwc26.com",
    notes: "40+ eateries internacionales, beer gardens, soccer zones. Partidos: México vs Korea, USA vs Australia.",
    food: "40+ restaurantes con cocina internacional",
    alcohol: true,
    amenities: "Beer garden, soccer zones familiares, 40+ eateries",
    active: true,
    status: "active",
  },
  {
    id: "la-city-of-downey",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone City of Downey",
    city: "Downey",
    country: "usa",
    venue: "Downtown Downey",
    address: "11242 Brookshire Ave, Downey, CA 90241",
    lat: 33.9401,
    lng: -118.1332,
    entry: "Gratis",
    datesOpen: "20 jun 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: "Community marketplace, food trucks, drinks, música. Partidos: Germany vs Côte d'Ivoire, Tunisia vs Japan.",
    food: "Food trucks y vendors locales",
    alcohol: true,
    amenities: "Community marketplace, música en vivo",
    active: true,
    status: "active",
  },
  {
    id: "la-venice-beach",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Venice Beach",
    city: "Los Ángeles",
    country: "usa",
    venue: "Venice Beach Boardwalk",
    address: "1800 Ocean Front Walk, Venice, CA 90291",
    lat: 33.9850,
    lng: -118.4695,
    entry: "Gratis",
    datesOpen: "10–11 jul 2026",
    officialUrl: "https://losangelesfwc26.com",
    registrationUrl: null,
    notes: "Fan zone en la playa durante rondas de knockout. Beachfront.",
    food: "Vendors locales del boardwalk",
    alcohol: true,
    amenities: "Vista a la playa del Pacífico, ambiente beachfront",
    active: true,
    status: "active",
  },
  {
    id: "pa-pittsburgh",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Pennsylvania Fan Zone Pittsburgh",
    city: "Pittsburgh",
    country: "usa",
    venue: "Acrisure Stadium",
    address: "100 Art Rooney Ave, Pittsburgh, PA 15212",
    lat: 40.4468,
    lng: -80.0158,
    entry: "Gratis con registro previo",
    datesOpen: "4, 5, 9 y 19 jul 2026",
    officialUrl: "https://phillyfwc26.com/pennsylvania-world-cup-fan-zones",
    registrationUrl: "https://phillyfwc26.com/pennsylvania-world-cup-fan-zones",
    notes: "Dentro del estadio de los Steelers NFL. Capacidad 5,000 personas. Organizado por Philadelphia Soccer 2026 y Visit PA.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Dentro de estadio NFL, pantallas gigantes, capacidad 5,000",
    active: true,
    status: "active",
  },
  {
    id: "pa-reading",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Pennsylvania Fan Zone Reading",
    city: "Reading",
    country: "usa",
    venue: "Santander Arena",
    address: "700 Penn St, Reading, PA 19602",
    lat: 40.3357,
    lng: -75.9269,
    entry: "Gratis con registro previo",
    datesOpen: "3–4 y 18–19 jul 2026",
    officialUrl: "https://phillyfwc26.com/pennsylvania-world-cup-fan-zones",
    registrationUrl: "https://phillyfwc26.com/pennsylvania-world-cup-fan-zones",
    notes: "Block party en Penn Street incluido. Organizado por Philadelphia Soccer 2026 y Visit PA.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Arena + block party exterior",
    active: true,
    status: "active",
  },
  {
    id: "pa-scranton",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Pennsylvania Fan Zone Scranton",
    city: "Scranton",
    country: "usa",
    venue: "Lackawanna County Courthouse Square",
    address: "200 N Washington Ave, Scranton, PA 18503",
    lat: 41.4090,
    lng: -75.6624,
    entry: "Gratis con registro previo",
    datesOpen: "3, 4, 5, 6, 18 y 19 jul 2026",
    officialUrl: "https://phillyfwc26.com/pennsylvania-world-cup-fan-zones",
    registrationUrl: "https://phillyfwc26.com/pennsylvania-world-cup-fan-zones",
    notes: "Organizado por Philadelphia Soccer 2026 y Visit PA.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Plaza al aire libre, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ma-franklin-fanzone",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "MetroWest Regional Fan Zone — Franklin",
    city: "Franklin",
    country: "usa",
    venue: "Franklin Town Common y Hayward Manor",
    address: "1 School St, Franklin, MA 02038",
    lat: 42.0834,
    lng: -71.3967,
    entry: "Gratis con registro previo",
    datesOpen: "24–25 jun 2026",
    officialUrl: "https://www.metrowestvisitors.org/world-cup",
    registrationUrl: "https://www.metrowestvisitors.org/world-cup",
    notes: "Avalado oficialmente por Boston 26. Organizado por MetroWest Visitors Bureau.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Town Common al aire libre, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ma-boston-common",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Boston Community Watch Party — Boston Common",
    city: "Boston",
    country: "usa",
    venue: "Parkman Bandstand, Boston Common",
    address: "139 Tremont St, Boston, MA 02111",
    lat: 42.3554,
    lng: -71.0655,
    entry: "Gratis",
    datesOpen: "19 jun 2026",
    officialUrl: "https://www.boston.gov/news/mayor-michelle-wu-announces-community-watch-parties",
    registrationUrl: null,
    notes: "Watch party comunitaria avalada por Boston 26. Organizada por la alcaldía de Boston.",
    food: "Vendors locales",
    alcohol: false,
    amenities: "Parque histórico al aire libre, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ma-dorchester",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Boston Community Watch Party — Dorchester",
    city: "Boston",
    country: "usa",
    venue: "Town Field, Dorchester",
    address: "585 Columbia Rd, Boston, MA 02125",
    lat: 42.3175,
    lng: -71.0573,
    entry: "Gratis",
    datesOpen: "15 jun 2026",
    officialUrl: "https://www.boston.gov/news/mayor-michelle-wu-announces-community-watch-parties",
    registrationUrl: null,
    notes: "Watch party comunitaria avalada por Boston 26.",
    food: "Vendors locales",
    alcohol: false,
    amenities: "Parque al aire libre, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ma-east-boston",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Boston Community Watch Party — East Boston",
    city: "Boston",
    country: "usa",
    venue: "East Boston Memorial Stadium",
    address: "84 Meridian St, East Boston, MA 02128",
    lat: 42.3724,
    lng: -71.0389,
    entry: "Gratis",
    datesOpen: "27 jun 2026",
    officialUrl: "https://www.boston.gov/news/mayor-michelle-wu-announces-community-watch-parties",
    registrationUrl: null,
    notes: "Watch party comunitaria avalada por Boston 26.",
    food: "Vendors locales",
    alcohol: false,
    amenities: "Estadio al aire libre, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "wa-seattle-soccer-house",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Seattle Soccer House — Pacific Place",
    city: "Seattle",
    country: "usa",
    venue: "Pacific Place Mall",
    address: "600 Pine St, Seattle, WA 98101",
    lat: 47.6115,
    lng: -122.3363,
    entry: "Gratis",
    datesOpen: "Jun 11 – Jul 6 2026, diario durante el torneo",
    officialUrl: "https://seattlefwc26.org/events/seattle-fan-celebrations",
    registrationUrl: null,
    notes: "Pantalla interna gigante de 4 pisos. Operado por Seattle FWC26.",
    food: "Vendors del mall",
    alcohol: true,
    amenities: "Pantalla gigante 4 pisos, interior climatizado",
    active: true,
    status: "active",
  },
  {
    id: "wa-seattle-match-day-live",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Seattle Match Day Live — Victory Hall SODO",
    city: "Seattle",
    country: "usa",
    venue: "Victory Hall, SODO",
    address: "1201 1st Ave S, Seattle, WA 98134",
    lat: 47.5888,
    lng: -122.3317,
    entry: "Gratis",
    datesOpen: "Jun 11 – Jul 19 2026, durante todo el torneo",
    officialUrl: "https://seattlefwc26.org/events/seattle-fan-celebrations",
    registrationUrl: null,
    notes: "Operado junto a los Seattle Mariners.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Pantallas gigantes, ambiente deportivo",
    active: true,
    status: "active",
  },
];

export async function seedUsaExpansion2026(): Promise<number> {
  await Promise.all(
    USA_EXPANSION_2026.map(({ id, ...data }) =>
      setDoc(doc(db, "wc2026_fanzones", id), { ...data, updatedAt: serverTimestamp() })
    )
  );
  console.log(`seedUsaExpansion2026 complete — ${USA_EXPANSION_2026.length} documents written.`);
  return USA_EXPANSION_2026.length;
}

// ─── ENTRY TYPE PATCHES — Mayo 2026 ───────────────────────────────────────────
// Agrega entryType (y price donde aplica) a documentos USA existentes.
// Valores posibles: "walk_in" | "registration_required" | "paid"
const ENTRY_TYPE_PATCHES: PatchRow[] = [
  { id: "fan-festival-philadelphia",  entryType: "registration_required" },
  { id: "fan-festival-dallas",        entryType: "walk_in" },
  { id: "fan-festival-houston",       entryType: "walk_in" },
  { id: "fan-festival-kansas-city",   entryType: "registration_required" },
  { id: "fan-festival-miami",         entryType: "walk_in" },
  { id: "fan-festival-atlanta",       entryType: "registration_required" },
  { id: "fan-festival-boston",        entryType: "registration_required" },
  { id: "fan-festival-los-angeles",   entryType: "paid", price: "$10 GA · $30 VIP" },
  { id: "fan-zone-queens-ny",         entryType: "registration_required" },
  { id: "fan-village-rockefeller-ny", entryType: "walk_in" },
  { id: "fan-hub-harrison-nj",        entryType: "paid", price: "$10 · Niños ≤12 gratis" },
  { id: "ny-brooklyn",                entryType: "registration_required" },
  { id: "ny-bronx",                   entryType: "walk_in" },
  { id: "ny-staten-island",           entryType: "walk_in" },
  { id: "la-union-station",           entryType: "walk_in" },
  { id: "la-hansen-dam",              entryType: "walk_in" },
  { id: "la-magic-johnson-park",      entryType: "walk_in" },
  { id: "la-whittier-narrows",        entryType: "walk_in" },
  { id: "la-fairplex",                entryType: "registration_required" },
  { id: "la-west-harbor",             entryType: "registration_required" },
  { id: "la-burbank",                 entryType: "walk_in", notes: "VIP $300+ con viewing lounge y concierto los días 18-19 jul" },
  { id: "wa-bellingham",              entryType: "walk_in" },
  { id: "wa-tacoma",                  entryType: "walk_in" },
  { id: "wa-spokane",                 entryType: "registration_required" },
  { id: "wa-everett",                 entryType: "walk_in" },
  { id: "wa-olympia",                 entryType: "paid", price: "$10 entrada general · Niños ≤12 gratis" },
  { id: "wa-yakima",                  entryType: "walk_in" },
  { id: "wa-bremerton",               entryType: "walk_in" },
  { id: "wa-tri-cities",              entryType: "walk_in" },
  { id: "adidas-home-soccer-nyc",     entryType: "walk_in" },
  { id: "adidas-home-soccer-la",      entryType: "registration_required", notes: "Ticketmaster desde Jun 1 para concierto Peso Pluma" },
  { id: "adidas-home-soccer-houston", entryType: "walk_in" },
  { id: "adidas-home-soccer-atlanta", entryType: "walk_in" },
];

export async function patchUsaEntryTypes(): Promise<number> {
  await Promise.all(
    ENTRY_TYPE_PATCHES.map(({ id, ...data }) =>
      setDoc(
        doc(db, "wc2026_fanzones", id),
        { ...data, updatedAt: serverTimestamp() },
        { merge: true }
      )
    )
  );
  console.log(`patchUsaEntryTypes complete — ${ENTRY_TYPE_PATCHES.length} documents patched.`);
  return ENTRY_TYPE_PATCHES.length;
}

// ─── MÉXICO EXPANSION — Mayo 2026 ─────────────────────────────────────────────
// 1 nuevo Fan Zone privado: Campo Marte 26 (festival privado con conciertos)
const MEXICO_EXPANSION_2026: Array<{ id: string } & SeedRow> = [
  {
    id: "cdmx-campo-marte",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Campo Marte 26",
    city: "Ciudad de México",
    country: "mexico",
    venue: "Campo Marte",
    address: "Av. Ejército Nacional, Polanco, Ciudad de México",
    lat: 19.4326,
    lng: -99.1964,
    entry: "Desde $400 pesos por día",
    entryType: "paid",
    price: "$400 pesos/día · VIP $1,000/día · Fin de semana desde $1,000 · Semanal desde $2,000",
    datesOpen: "11 jun – 19 jul 2026 (39 días)",
    officialUrl: "https://campomarte26.com",
    registrationUrl: "https://www.ticketmaster.com.mx",
    notes: "Festival privado no oficial de FIFA. Music Pavilion con 17 conciertos: Parcels, The Avalanches, L'Impératrice, Modeselektor, Polo & Pan, Purple Disco Machine. Gastronomía de las 32 entidades mexicanas rotando semanalmente. Partidos en pantalla gigante por las mañanas y tardes, conciertos por las noches. Patrocinado por Santander. Junto al Auditorio Nacional.",
    food: "Gastronomía de las 32 entidades mexicanas, cambia cada semana",
    alcohol: true,
    amenities: "17 conciertos en vivo, pantallas gigantes para los 104 partidos, gastronomía premium, Music Pavilion",
    active: true,
    status: "active",
  },
];

export async function seedMexicoExpansion2026(): Promise<number> {
  await Promise.all(
    MEXICO_EXPANSION_2026.map(({ id, ...data }) =>
      setDoc(doc(db, "wc2026_fanzones", id), { ...data, updatedAt: serverTimestamp() })
    )
  );
  console.log(`seedMexicoExpansion2026 complete — ${MEXICO_EXPANSION_2026.length} documents written.`);
  return MEXICO_EXPANSION_2026.length;
}

// ─── MÉXICO ENTRY TYPE PATCHES — Mayo 2026 ────────────────────────────────────
// Agrega entryType: "walk_in" a todos los Fan Zones de México existentes.
const MEXICO_ENTRY_TYPE_PATCHES: PatchRow[] = [
  { id: "fan-festival-cdmx",          entryType: "walk_in", notes: "Sin registro previo confirmado. Zona VIP estilo F1 disponible. SIN alcohol en zona general — solo cerveza cero. Única excepción: bar completo en zona VIP." },
  { id: "fan-festival-monterrey",     entryType: "walk_in", price: "Gratis walk-in · Zona preferente desde $850 pesos · VIP disponible en Ticketmaster" },
  { id: "fan-festival-guadalajara",   entryType: "walk_in" },
  { id: "adidas-home-soccer-cdmx",    entryType: "walk_in" },
  { id: "adidas-home-soccer-gdl",     entryType: "walk_in" },
  { id: "adidas-home-soccer-mty",     entryType: "walk_in" },
  { id: "cdmx-chapultepec-cricri",    entryType: "walk_in" },
  { id: "cdmx-utopia-meyehualco",     entryType: "walk_in" },
  { id: "cdmx-campos-revolucion",     entryType: "walk_in" },
  { id: "cdmx-garibaldi",             entryType: "walk_in" },
  { id: "cdmx-deportivo-galeana",     entryType: "walk_in" },
  { id: "cdmx-iztapalapa",            entryType: "walk_in" },
  { id: "cdmx-coyoacan",              entryType: "walk_in" },
  { id: "cdmx-tlalpan",               entryType: "walk_in" },
  { id: "cdmx-xochimilco",            entryType: "walk_in" },
  { id: "cdmx-bombilla",              entryType: "walk_in" },
  { id: "cdmx-tezozomoc",             entryType: "walk_in" },
  { id: "cdmx-parque-americas",       entryType: "walk_in" },
  { id: "cdmx-consolacion",           entryType: "walk_in" },
  { id: "cdmx-san-mateo-atenco",      entryType: "walk_in" },
  { id: "cdmx-leandro-valle",         entryType: "walk_in" },
  { id: "cdmx-unidad-independencia",  entryType: "walk_in" },
  { id: "cdmx-tlahuac",               entryType: "walk_in" },
  { id: "cdmx-vivanco",               entryType: "walk_in" },
  { id: "cdmx-eduardo-molina",        entryType: "walk_in" },
  { id: "gdl-parque-rojo",            entryType: "walk_in" },
  { id: "gdl-parque-la-mujer",        entryType: "walk_in" },
  { id: "gdl-parque-ninas-ninos",     entryType: "walk_in" },
  { id: "gdl-plaza-las-americas",     entryType: "walk_in" },
];

export async function patchMexicoEntryTypes(): Promise<number> {
  await Promise.all(
    MEXICO_ENTRY_TYPE_PATCHES.map(({ id, ...data }) =>
      setDoc(
        doc(db, "wc2026_fanzones", id),
        { ...data, updatedAt: serverTimestamp() },
        { merge: true }
      )
    )
  );
  console.log(`patchMexicoEntryTypes complete — ${MEXICO_ENTRY_TYPE_PATCHES.length} documents patched.`);
  return MEXICO_ENTRY_TYPE_PATCHES.length;
}

// ─── CANADÁ EXPANSION — Mayo 2026 ─────────────────────────────────────────────
// 2 nuevos Fan Zones de Vancouver: Granville Island y Shipyards North Vancouver
const CANADA_EXPANSION_2026: Array<{ id: string } & SeedRow> = [
  {
    id: "canada-granville-island",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Fan Zone Granville Island",
    city: "Vancouver",
    country: "canada",
    venue: "Granville Island Public Market",
    address: "1661 Duranleau St, Vancouver, BC V6H 3S3",
    lat: 49.2718,
    lng: -123.1342,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "Jun 11 – Jul 19 2026 (92 partidos confirmados)",
    officialUrl: "https://vancouverfwc26.ca",
    registrationUrl: null,
    notes: "Transmiten 92 partidos del torneo. Capacidad 1,000 personas. Ambiente artístico e íntimo de Granville Island.",
    food: "Vendors y restaurantes de Granville Island Public Market",
    alcohol: true,
    amenities: "Pantallas gigantes, capacidad 1,000 personas, ambiente artístico waterfront",
    active: true,
    status: "active",
  },
  {
    id: "canada-house-north-vancouver",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Canada House — Shipyards North Vancouver",
    city: "North Vancouver",
    country: "canada",
    venue: "The Shipyards",
    address: "125 Victory Ship Way, North Vancouver, BC V7L 0B1",
    lat: 49.3098,
    lng: -123.0784,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "Jun 11 – Jul 19 2026",
    officialUrl: "https://vancouverfwc26.ca",
    registrationUrl: null,
    notes: "Capacidad 5,000 personas. Waterfront con vista a Vancouver. Diferente al FIFA Fan Festival oficial de PNE.",
    food: "Vendors locales de The Shipyards",
    alcohol: true,
    amenities: "Capacidad 5,000, waterfront, vista a Vancouver, pantallas gigantes",
    active: true,
    status: "active",
  },
];

export async function seedCanadaExpansion2026(): Promise<number> {
  await Promise.all(
    CANADA_EXPANSION_2026.map(({ id, ...data }) =>
      setDoc(doc(db, "wc2026_fanzones", id), { ...data, updatedAt: serverTimestamp() })
    )
  );
  console.log(`seedCanadaExpansion2026 complete — ${CANADA_EXPANSION_2026.length} documents written.`);
  return CANADA_EXPANSION_2026.length;
}

// ─── CANADÁ ENTRY TYPE PATCHES — Mayo 2026 ────────────────────────────────────
const CANADA_ENTRY_TYPE_PATCHES: PatchRow[] = [
  { id: "canada-vancouver",           entryType: "walk_in",               price: "Gratis GA · Anfiteatro: boletos pagados en Ticketmaster · Lawn desde $44 CAD · Reserved desde $115 CAD" },
  { id: "canada-toronto",             entryType: "registration_required", price: "Gratis GA con registro · Premium $100–$300 CAD con entrada garantizada" },
  { id: "adidas-home-soccer-toronto", entryType: "walk_in" },
];

export async function patchCanadaEntryTypes(): Promise<number> {
  await Promise.all(
    CANADA_ENTRY_TYPE_PATCHES.map(({ id, ...data }) =>
      setDoc(
        doc(db, "wc2026_fanzones", id),
        { ...data, updatedAt: serverTimestamp() },
        { merge: true }
      )
    )
  );
  console.log(`patchCanadaEntryTypes complete — ${CANADA_ENTRY_TYPE_PATCHES.length} documents patched.`);
  return CANADA_ENTRY_TYPE_PATCHES.length;
}

// ─── BAY AREA EXPANSION — Mayo 2026 ──────────────────────────────────────────
// 12 nuevos Fan Zones: eventos específicos, marchas de fans, Pride House, Oakland
const BAY_AREA_EXPANSION_2026 = [
  {
    id: "ba-alameda-county-fair",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Summer Soccer Celebration — Alameda County Fair",
    city: "Pleasanton",
    country: "bay_area",
    venue: "Alameda County Fairgrounds",
    address: "4501 Pleasanton Ave, Pleasanton, CA 94566",
    lat: 37.6524,
    lng: -121.8747,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "Jun 19 – Jul 11 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Uno de los venues más grandes del Bay Area fuera de SF. Familiar, con espacio amplio y ambiente de feria.",
    food: "Food vendors de la feria",
    alcohol: true,
    amenities: "Pantallas gigantes, espacio familiar amplio, ambiente de feria",
    active: true,
    status: "active",
  },
  {
    id: "ba-pleasant-hill",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Downtown Pleasant Hill Community Fan Celebration",
    city: "Pleasant Hill",
    country: "bay_area",
    venue: "Downtown Pleasant Hill",
    address: "110 Gregory Lane, Pleasant Hill, CA 94523",
    lat: 37.9477,
    lng: -122.0608,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "11 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Celebración de apertura del Mundial. Evento comunitario para Contra Costa County.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Pantallas gigantes, ambiente comunitario",
    active: true,
    status: "active",
  },
  {
    id: "ba-east-palo-alto",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "East Palo Alto Community Soccer Watch Party",
    city: "East Palo Alto",
    country: "bay_area",
    venue: "East Palo Alto",
    address: "East Palo Alto, CA 94303",
    lat: 37.4680,
    lng: -122.1411,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "12 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Watch party comunitaria organizada para la comunidad latina de East Palo Alto.",
    food: "Vendors locales",
    alcohol: false,
    amenities: "Pantallas gigantes, evento comunitario latino",
    active: true,
    status: "active",
  },
  {
    id: "ba-berkeley-watch-party",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Berkeley Celebrity Watch Party — USA vs Paraguay",
    city: "Berkeley",
    country: "bay_area",
    venue: "Berkeley",
    address: "Berkeley, CA 94710",
    lat: 37.8716,
    lng: -122.2727,
    entry: "Gratis con RSVP",
    entryType: "registration_required",
    datesOpen: "12 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    notes: "Watch party oficial para USA vs Paraguay con apariciones especiales.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Pantallas gigantes, apariciones especiales",
    active: true,
    status: "active",
  },
  {
    id: "ba-cultura-fc-oakland",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Cultura FC — Block15 Jack London Square",
    city: "Oakland",
    country: "bay_area",
    venue: "Block15 Jack London Square",
    address: "334 Water St, Oakland, CA 94607",
    lat: 37.7955,
    lng: -122.2760,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "23–25 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Celebración de fútbol, arte y cultura co-organizada por Oakland Roots y Oakland Soul. Único en su tipo en el Bay Area.",
    food: "Food vendors locales de Jack London Square",
    alcohol: true,
    amenities: "Arte, música, cultura, pantallas gigantes, ambiente único",
    active: true,
    status: "active",
  },
  {
    id: "ba-oakland-marriott",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Oakland World Cup Watch Party — Oakland Marriott",
    city: "Oakland",
    country: "bay_area",
    venue: "Oakland Marriott City Center",
    address: "1001 Broadway, Oakland, CA 94607",
    lat: 37.8044,
    lng: -122.2712,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "12 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Watch party para USA vs Paraguay organizado por Oakland Sports Group.",
    food: "Menú del hotel y vendors",
    alcohol: true,
    amenities: "Pantallas gigantes, ambiente de hotel",
    active: true,
    status: "active",
  },
  {
    id: "ba-usa-australia-oakland",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "USA vs Australia Watch Party Oakland",
    city: "Oakland",
    country: "bay_area",
    venue: "Oakland",
    address: "Oakland, CA 94612",
    lat: 37.8044,
    lng: -122.2712,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "19 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Watch party oficial para USA vs Australia. Venue exacto por confirmar.",
    food: "Por confirmar",
    alcohol: true,
    amenities: "Pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ba-pride-house-beaux",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Pride House SF — Big Gay Watch Party at Beaux",
    city: "San Francisco",
    country: "bay_area",
    venue: "Beaux",
    address: "2344 Market St, San Francisco, CA 94114",
    lat: 37.7632,
    lng: -122.4348,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "12 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Watch party oficial de Pride House SF para la comunidad LGBTQ+.",
    food: "Menú del bar",
    alcohol: true,
    amenities: "Ambiente LGBTQ+ friendly, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ba-pride-house-east-cut",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Pride House Fan Zone — The Crossing at East Cut",
    city: "San Francisco",
    country: "bay_area",
    venue: "The Crossing at East Cut",
    address: "160 Natoma St, San Francisco, CA 94105",
    lat: 37.7873,
    lng: -122.3964,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "19 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Watch party oficial de Pride House SF para USA vs Australia.",
    food: "Vendors locales",
    alcohol: true,
    amenities: "Ambiente LGBTQ+ friendly, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ba-sf-pride-block-party",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Official SF Pride Block Party & Pride House Watch Party",
    city: "San Francisco",
    country: "bay_area",
    venue: "San Francisco Pride",
    address: "Market St & Beale St, San Francisco, CA 94105",
    lat: 37.7909,
    lng: -122.3971,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "25 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Coincide con SF Pride. Watch party oficial con block party incluido.",
    food: "Vendors del evento Pride",
    alcohol: true,
    amenities: "Block party, ambiente Pride, pantallas gigantes",
    active: true,
    status: "active",
  },
  {
    id: "ba-fan-march-usa",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Team USA Soccer Fan March — Crane Cove to Thrive City",
    city: "San Francisco",
    country: "bay_area",
    venue: "Crane Cove Park → Thrive City",
    address: "1201 Illinois St, San Francisco, CA 94107",
    lat: 37.7574,
    lng: -122.3870,
    entry: "Gratis con RSVP",
    entryType: "registration_required",
    datesOpen: "12 jun 2026 — 4:30pm",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    notes: "Marcha oficial de fans de Team USA de Crane Cove hasta Thrive City. Sale a las 4:30pm.",
    food: null,
    alcohol: false,
    amenities: "Marcha fan oficial, ambiente de previa del partido",
    active: true,
    status: "active",
  },
  {
    id: "ba-fan-march-mexico",
    tournament: "world_cup_2026",
    type: "fan_zone",
    name: "Team Mexico Soccer Fan March — SF",
    city: "San Francisco",
    country: "bay_area",
    venue: "San Francisco → Thrive City",
    address: "San Francisco, CA 94107",
    lat: 37.7680,
    lng: -122.3880,
    entry: "Gratis",
    entryType: "walk_in",
    datesOpen: "18 jun 2026",
    officialUrl: "https://www.sfbayareafwc26.com/bay-area-events",
    registrationUrl: null,
    notes: "Marcha oficial de fans de Team Mexico hacia Thrive City para el partido México vs Corea del Sur.",
    food: null,
    alcohol: false,
    amenities: "Marcha fan oficial, ambiente de previa del partido",
    active: true,
    status: "active",
  },
];

export async function seedBayAreaExpansion2026(): Promise<number> {
  await Promise.all(
    BAY_AREA_EXPANSION_2026.map(({ id, ...data }) =>
      setDoc(doc(db, "wc2026_fanzones", id), { ...data, updatedAt: serverTimestamp() })
    )
  );
  console.log(`seedBayAreaExpansion2026 complete — ${BAY_AREA_EXPANSION_2026.length} documents written.`);
  return BAY_AREA_EXPANSION_2026.length;
}

// ─── BAY AREA ENTRY TYPE PATCHES — Mayo 2026 ─────────────────────────────────
// Agrega entryType a los 20 Fan Zones Bay Area existentes.
const BAY_AREA_ENTRY_TYPE_PATCHES: PatchRow[] = [
  { id: "fan-zone-thrive-city-sf",       entryType: "walk_in" },
  { id: "fan-zone-san-pedro-square-sj",  entryType: "registration_required", registrationUrl: "https://www.sfbayareafwc26.com/bay-area-events" },
  { id: "sf-china-basin",                entryType: "walk_in" },
  { id: "sf-pier39",                     entryType: "walk_in" },
  { id: "oak-raimondi-park",             entryType: "registration_required", registrationUrl: "https://ticketleap.com" },
  { id: "ba-spark-social-sf",            entryType: "walk_in" },
  { id: "ba-treasure-island-gold-bar",   entryType: "registration_required", registrationUrl: "https://ticketfairy.com" },
  { id: "ba-walnut-creek-lesher",        entryType: "registration_required" },
  { id: "ba-richmond-red-oak",           entryType: "walk_in" },
  { id: "ba-richmond-east-brother",      entryType: "walk_in" },
  { id: "ba-san-carlos-wheeler",         entryType: "walk_in" },
  { id: "ba-redwood-city-courthouse",    entryType: "walk_in" },
  { id: "ba-san-mateo-central-park",     entryType: "walk_in" },
  { id: "ba-santana-row",                entryType: "walk_in" },
  { id: "ba-morgan-hill",                entryType: "walk_in" },
  { id: "ba-milpitas",                   entryType: "walk_in" },
  { id: "ba-santa-cruz-boardwalk",       entryType: "walk_in" },
  { id: "ba-downtown-oakland",           entryType: "walk_in" },
  { id: "ba-jackson-playground-sf",      entryType: "walk_in" },
];

export async function patchBayAreaEntryTypes(): Promise<number> {
  await Promise.all(
    BAY_AREA_ENTRY_TYPE_PATCHES.map(({ id, ...data }) =>
      setDoc(
        doc(db, "wc2026_fanzones", id),
        { ...data, updatedAt: serverTimestamp() },
        { merge: true }
      )
    )
  );
  console.log(`patchBayAreaEntryTypes complete — ${BAY_AREA_ENTRY_TYPE_PATCHES.length} documents patched.`);
  return BAY_AREA_ENTRY_TYPE_PATCHES.length;
}

// ─── CAMBIO 3 — Eliminar champions-splash-thrive ──────────────────────────────
export async function deleteChampionsSplashThrive(): Promise<void> {
  await deleteDoc(doc(db, "wc2026_fanzones", "champions-splash-thrive"));
  console.log("Deleted: champions-splash-thrive");
}

// ─── CAMBIO 4 — Listar y borrar venues fuera del Bay Area ────────────────────
const BAY_AREA_ID_PREFIXES = ["ba-", "sf-", "oak-", "fan-zone-"];

export async function listNonBayAreaFanZones(): Promise<Array<{ id: string; name: string; country: string }>> {
  const snap = await getDocs(collection(db, "wc2026_fanzones"));
  const nonBayArea = snap.docs
    .filter((d) => d.data().country !== "bay_area")
    .map((d) => ({ id: d.id, name: (d.data().name as string) ?? "(sin nombre)", country: (d.data().country as string) ?? "?" }));
  nonBayArea.forEach((z) => console.log(`[non-bay-area] ${z.id} | ${z.name} | ${z.country}`));
  console.log(`listNonBayAreaFanZones — ${nonBayArea.length} documentos fuera del Bay Area.`);
  return nonBayArea;
}

export async function deleteNonBayAreaFanZones(): Promise<string[]> {
  const snap = await getDocs(collection(db, "wc2026_fanzones"));
  const toDelete = snap.docs.filter((d) => {
    if (d.data().country === "bay_area") return false;
    if (BAY_AREA_ID_PREFIXES.some((p) => d.id.startsWith(p))) return false;
    return true;
  });
  await Promise.all(toDelete.map((d) => deleteDoc(d.ref)));
  const deleted = toDelete.map((d) => d.id);
  deleted.forEach((id) => console.log(`Deleted: ${id}`));
  console.log(`deleteNonBayAreaFanZones complete — ${deleted.length} documentos eliminados.`);
  return deleted;
}
